import generatedRaw from "./campaign-finance-generated.json";

export interface CandidateFinance {
  name: string;
  office: string;
  level: "federal" | "state" | "houston" | "county";
  party: "D" | "R";
  cash: number;
  raised?: number;
  spent?: number;
  investments?: number;
  loans?: number;
  asOf: string;
  incumbent?: boolean;
  filingUrl?: string;
}

const TEC = (name: string) => `https://www.ethics.state.tx.us/search/cf/list.php?name=${encodeURIComponent(name)}&type=cand`;
const FEC = (id: string) => `https://www.fec.gov/data/candidate/${id}/`;

export const FINANCE_DATA: CandidateFinance[] = [
  // Federal
  { name: "James Talarico",        office: "U.S. Senate (D nominee)",        level: "federal",  party: "D", cash: 9858865, raised: 40284109, spent: 30425243, asOf: "Apr 2026", incumbent: false, filingUrl: "https://www.fec.gov/data/candidate/S6TX00462/" },
  { name: "Jasmine Crockett",      office: "U.S. Senate (lost D runoff to Talarico)", level: "federal",  party: "D", cash: 633086,   raised: 11092295,  spent: 10459209,  asOf: "Apr 2026", incumbent: false, filingUrl: "https://www.fec.gov/data/candidate/S6TX00338/" },
  { name: "John Cornyn",           office: "U.S. Senator (lost R runoff. Term ends Jan 2027)", level: "federal", party: "R", cash: 8200000, raised: 9000000, spent: 15800000, asOf: "Apr 2026", incumbent: true, filingUrl: FEC("S0TX00999") },
  { name: "Ken Paxton",            office: "U.S. Senate (R nominee)",        level: "federal",  party: "R", cash: 2600000,   raised: 2200000,  spent: 3200000,  asOf: "Apr 2026", incumbent: false, filingUrl: FEC("S4TX00462") },
  { name: "Lizzie Fletcher",       office: "U.S. Rep CD-07",                 level: "federal",  party: "D", cash: 1750893,   asOf: "Apr 2026", incumbent: true,  filingUrl: FEC("H8TX07139") },
  { name: "Shaun Finnie",          office: "U.S. Rep CD-02 (D nominee)",     level: "federal",  party: "D", cash: 1543080,   asOf: "Apr 2026", incumbent: false, filingUrl: FEC("H4TX02177") },
  { name: "Al Green",              office: "U.S. Rep CD-9 (ran for CD-18 in 2026 D runoff; lost to Menefee)", level: "federal",  party: "D", cash: 264570,    asOf: "Apr 2026", incumbent: true,  filingUrl: FEC("H4TX09090") },
  { name: "Christian Menefee",     office: "U.S. Rep CD-18",                 level: "federal",  party: "D", cash: 255858,    asOf: "Apr 2026", incumbent: true,  filingUrl: FEC("H6TX18232") },
  { name: "Sylvia Garcia",         office: "U.S. Rep CD-29",                 level: "federal",  party: "D", cash: 175662,    raised: 903166, spent: 1099257, asOf: "Apr 2026", incumbent: true,  filingUrl: FEC("H8TX29049") },
  // State
  { name: "Greg Abbott",           office: "Governor",                        level: "state",    party: "R", cash: 105700000, raised: 22700000, asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Greg Abbott") },
  { name: "Dan Patrick",          office: "Lt. Governor (seeking 4th term)",  level: "state",    party: "R", cash: 37701658, raised: 1799374, spent: 951331,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Dan Patrick") },
  { name: "Vikki Goodwin",        office: "Lt. Governor (D nominee)",         level: "state",    party: "D", cash: 161130, raised: 367962, spent: 491789,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Vikki Goodwin") },
  { name: "Don Huffines",         office: "Comptroller (R nominee)",          level: "state",    party: "R", cash: 11773001, raised: 1043287, spent: 3981450,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Don Huffines") },
  { name: "Sarah Eckhardt",       office: "Comptroller (D nominee)",          level: "state",    party: "D", cash: 183692, raised: 113110, spent: 84128,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Sarah Eckhardt") },
  { name: "Mayes Middleton",      office: "Attorney General (R nominee)",     level: "state",    party: "R", cash: 10000000, asOf: "Jan 2026 est.", incumbent: false, filingUrl: TEC("Mayes Middleton") },
  { name: "Nathan Johnson",       office: "Attorney General (D nominee)",     level: "state",    party: "D", cash: 757681, raised: 652819, spent: 349080,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Nathan Johnson") },
  { name: "Brett Ligon",          office: "State Senator SD-4 (won May special election)", level: "state", party: "R", cash: 227291, raised: 254906, spent: 170238, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Brett Ligon") },
  { name: "Carol Alvarado",        office: "State Senator SD-6 (not on 2026 ballot)", level: "state",    party: "D", cash: 1569982, raised: 100369, spent: 116255, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Carol Alvarado") },
  { name: "Borris Miles",          office: "State Senator SD-13",            level: "state",    party: "D", cash: 6379,   raised: 58673, spent: 52295, loans: 9500, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Borris Miles") },
  { name: "Joan Huffman",          office: "Ran for Texas AG (SD-17 term to 2029)", level: "state", party: "R", cash: 2718093, raised: 522017, spent: 865632,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Joan Huffman") },
  { name: "Senfronia Thompson",    office: "State Rep HD-141",               level: "state",    party: "D", cash: 891576,  raised: 27456, spent: 143959, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Senfronia Thompson") },
  { name: "Harold Dutton Jr.",      office: "State Rep HD-142",               level: "state",    party: "D", cash: 137569, raised: 36750, spent: 22195,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Harold Dutton Jr.") },
  { name: "Gene Wu",               office: "State Rep HD-137",               level: "state",    party: "D", cash: 104918, raised: 259197, spent: 176116, loans: 10000, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Eugene Wu") },
  { name: "Jolanda Jones",         office: "State Rep HD-147",               level: "state",    party: "D", cash: 29697, raised: 19354, spent: 19893,    asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Jolanda Jones") },
  { name: "Lauren Ashley Simmons", office: "State Rep HD-146",               level: "state",    party: "D", cash: 18480,  raised: 66819, spent: 73438, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lauren Ashley Simmons") },
  { name: "Christina Morales",     office: "State Rep HD-145",               level: "state",    party: "D", cash: 31610, raised: 16885, spent: 13422,    asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Christina Morales") },
  { name: "Charlene Ward Johnson", office: "State Rep HD-139",               level: "state",    party: "D", cash: 5377,   raised: 24489, spent: 18372, loans: 20000, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Charlene Ward Johnson") },
  { name: "Jon Rosenthal",         office: "Texas Railroad Commissioner (D nominee)", level: "state",    party: "D", cash: 30063,  raised: 59723, spent: 58710, asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Jon Rosenthal") },
  { name: "Lacey Hull",            office: "State Rep HD-138",               level: "state",    party: "R", cash: 379458, raised: 130057, spent: 88744,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lacey Hull") },
  { name: "Tom Oliverson",         office: "State Rep HD-130",               level: "state",    party: "R", cash: 478800,      asOf: "May 2026", incumbent: true,  filingUrl: TEC("Tom Oliverson") },
  { name: "Dennis Paul",           office: "State Senator SD-11 (R nominee)", level: "state",   party: "R", cash: 13425, raised: 20051, spent: 143472,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Dennis Paul") },
  { name: "Greg Bonnen",           office: "State Rep HD-24",                level: "state",    party: "R", cash: 1972303, raised: 175931, spent: 87230,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Greg Bonnen") },
  { name: "Mike Schofield",        office: "State Rep HD-132",               level: "state",    party: "R", cash: 132836, raised: 37220, spent: 34718,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Mike Schofield") },
  { name: "Penny Morales Shaw",    office: "State Rep HD-148",               level: "state",    party: "D", cash: 20327, raised: 31783, spent: 29831, loans: 4000, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Penny Morales Shaw") },
  { name: "Gina Hinojosa",         office: "Governor (D nominee)",            level: "state",    party: "D", cash: 617635,  asOf: "Feb 2026", incumbent: false, filingUrl: TEC("Gina Hinojosa") },
  { name: "Ann Johnson",           office: "State Rep HD-134",               level: "state",    party: "D", cash: 600906, raised: 206130, spent: 135087,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Ann Johnson") },
  { name: "Ana Hernandez",         office: "State Rep HD-143",               level: "state",    party: "D", cash: 448691,    asOf: "May 2026", incumbent: true,  filingUrl: TEC("Ana Hernandez") },
  { name: "Armando Walle",         office: "State Rep HD-140",               level: "state",    party: "D", cash: 239791, raised: 93700, spent: 88132, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Armando Walle") },
  { name: "Mary Ann Perez",        office: "State Rep HD-144",               level: "state",    party: "D", cash: 366459,    asOf: "May 2026", incumbent: true,  filingUrl: TEC("Mary Ann Perez") },
  { name: "Paul Bettencourt",      office: "State Senator SD-7 (not on 2026 ballot)", level: "state", party: "R", cash: 1118599, asOf: "Jan 2026", incumbent: true, filingUrl: TEC("Paul Bettencourt") },
  { name: "Molly Cook",            office: "State Senator SD-15",            level: "state",    party: "D", cash: 117879, raised: 50831, spent: 48727,    asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Molly Cook") },
  { name: "Charles Cunningham",    office: "State Rep HD-127",               level: "state",    party: "R", cash: 99950, raised: 7500, spent: 14912, loans: 40750,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Charles Cunningham") },
  { name: "Briscoe Cain",         office: "State Rep HD-128 (ran for CD-9)", level: "state",   party: "R", cash: 28323, raised: 20802, spent: 90114,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Briscoe Cain") },
  { name: "Mano DeAyala",         office: "State Rep HD-133",               level: "state",    party: "R", cash: 316067,    asOf: "May 2026", incumbent: true,  filingUrl: TEC("Emilio DeAyala") },
  { name: "Mark Dorazio",         office: "State Rep HD-150",               level: "state",    party: "R", cash: 404315, raised: 106299, spent: 24539, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Mark Dorazio") },
  { name: "Lois Kolkhorst",        office: "State Senator SD-18",            level: "state",    party: "R", cash: 3159564, raised: 102510, spent: 128026, asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lois Kolkhorst") },
  { name: "Valoree Swanson",      office: "State Rep HD-150 (former, 2017–2022)", level: "state",  party: "R", cash: 76987, raised: 19488, spent: 22509, asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Valoree Swanson") },
  { name: "A'Yonna Kellum",       office: "State Rep HD-150 (D nominee)",   level: "state",    party: "D", cash: 1,     raised: 750,   spent: 750,      asOf: "Dec 2025", incumbent: false, filingUrl: TEC("A'Yonna Kellum") },
  { name: "Hubert Vo",             office: "State Rep HD-149 (lost D runoff; holds seat through Jan 2027)", level: "state", party: "D", cash: 97961, asOf: "Jan 2026", incumbent: true, filingUrl: TEC("Hubert Vo") },
  { name: "Alma Allen",           office: "State Rep HD-131 (not seeking reelection)", level: "state", party: "D", cash: 23058, asOf: "Jan 2026", incumbent: true, filingUrl: TEC("Alma Allen") },
  { name: "Sam Harless",          office: "State Rep HD-126 (not seeking reelection)", level: "state", party: "R", cash: 0, asOf: "pending", incumbent: true, filingUrl: TEC("Sam Harless") },
  { name: "Darlene Breaux",        office: "State Rep HD-149 (D nominee)",   level: "state",    party: "D", cash: 8007,  raised: 11445, spent: 12665,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Darlene Breaux") },
  { name: "Shannon Dicely",        office: "State Senator SD-11 (D nominee)", level: "state",   party: "D", cash: 1890,  raised: 7880,  spent: 5027,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Shannon Dicely") },
  { name: "Stefanie Bord",         office: "State Rep HD-126 (D nominee)",   level: "state",    party: "D", cash: 2273,  raised: 4750,  spent: 6577,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Stefanie Bord") },
  { name: "Stan Stanart",          office: "State Rep HD-126 (R nominee)",   level: "state",    party: "R", cash: 67084, raised: 31496, spent: 12229,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Stan Stanart") },
  { name: "Staci Childs",          office: "State Rep HD-131 (D nominee)",   level: "state",    party: "D", cash: 3926,  raised: 45692, spent: 34819,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Staci Childs") },
  // 2026 state nominees and challengers
  { name: "Scott Bowen",           office: "State Rep HD-129 (R nominee)",   level: "state",    party: "R", cash: 54346, raised: 92616, spent: 112658, asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Scott Bowen") },
  { name: "Helen Zhou",            office: "State Rep HD-137 (R nominee)",   level: "state",    party: "R", cash: 22394, raised: 9046,  spent: 5717,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Helen Zhou") },
  { name: "Michelle Williams",     office: "State Rep HD-127 (D nominee)",   level: "state",    party: "D", cash: 0,     raised: 2919,  spent: 1904,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Michelle Williams") },
  { name: "Albert Wittliff",       office: "State Rep HD-129 (D nominee)",   level: "state",    party: "D", cash: 14527, raised: 21842, spent: 5287,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Herman Wittliff") },
  { name: "Brett Robinson",        office: "State Rep HD-130 (D nominee)",   level: "state",    party: "D", cash: 597,   raised: 0,     spent: 1802,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Brett Robinson") },
  { name: "Sara McGee",            office: "State Rep HD-132 (D nominee)",   level: "state",    party: "D", cash: 11714, raised: 22095, spent: 16586,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Sara McGee") },
  { name: "Mike Michna",           office: "State Rep HD-134 (R nominee)",   level: "state",    party: "R", cash: 748,   raised: 1471,  spent: 1473,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Michael Michna") },
  { name: "Tyler Smith",           office: "State Rep HD-138 (D nominee)",   level: "state",    party: "D", cash: 14442, raised: 22947, spent: 32639,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Tyler Smith") },
  { name: "Kyle Harding",          office: "State Rep HD-139 (R nominee)",   level: "state",    party: "R", cash: 0,     raised: 0,     spent: 750,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Dennis Kyle Harding") },
  { name: "Julie Hunt",            office: "State Rep HD-141 (R nominee)",   level: "state",    party: "R", cash: 50,    raised: 800,   spent: 785,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Julie Hunt") },
  { name: "Heidi Hall",            office: "State Rep HD-142 (R nominee)",   level: "state",    party: "R", cash: 0,     raised: 0,     spent: 750,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Heidi Hall") },
  { name: "Laura Garcia DeLeon",   office: "State Rep HD-140 (R nominee)",   level: "state",    party: "R", cash: 0,     asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Laura Garcia DeLeon") },
  { name: "Frank Salazar",         office: "State Rep HD-143 (R nominee)",   level: "state",    party: "R", cash: 0,     asOf: "pending", incumbent: false, filingUrl: TEC("Frank Salazar") },
  { name: "Dave Bennett",          office: "State Rep HD-149 (R nominee)",   level: "state",    party: "R", cash: 45854, asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Dave Bennett") },
  { name: "David Flores",          office: "State Rep HD-144 (R nominee)",   level: "state",    party: "R", cash: 0,     raised: 300,   spent: 750,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("David Flores") },
  { name: "Inocensia Moreno",      office: "State Rep HD-145 (R nominee)",   level: "state",    party: "R", cash: 50,    raised: 750,   spent: 0,      asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Inocensia Moreno") },
  { name: "Alexandria Butler",     office: "State Rep HD-146 (R nominee)",   level: "state",    party: "R", cash: 0,     asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Alexandria Butler") },
  { name: "Theodis Daniel",        office: "State Rep HD-147 (R nominee)",   level: "state",    party: "R", cash: 0,     asOf: "pending", incumbent: false, filingUrl: TEC("Theodis Daniel") },
  { name: "Amanda LaBrie",         office: "State Rep HD-148 (R nominee)",   level: "state",    party: "R", cash: 4907,  raised: 8940,  spent: 4423,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Amanda LaBrie") },
  { name: "Joseph L. Trahan",      office: "State Senator SD-15 (R nominee)", level: "state",   party: "R", cash: 7.35,  asOf: "2025-07-31", incumbent: false, filingUrl: TEC("Joseph Trahan") },
  { name: "Erica Gillum",          office: "State Senator SD-18 (D nominee)", level: "state",   party: "D", cash: 0,     raised: 1250,  spent: 1250,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Erica Gillum") },
  // 2026 open seat nominees
  { name: "Odus Evbagharu",        office: "State Rep HD-135 (D nominee)",   level: "state",    party: "D", cash: 17330, raised: 70850, spent: 48651,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Odus Evbagharu") },
  { name: "Liz Ramos",             office: "State Rep HD-135 (R nominee)",   level: "state",    party: "R", cash: 11915, raised: 7223,  spent: 4512,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Liz Ramos") },
  { name: "Desiree Klaus",         office: "State Rep HD-128 (D nominee)",   level: "state",    party: "D", cash: 624,   raised: 1995,  spent: 1346,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Desiree Klaus") },
  { name: "Tom Butler",            office: "State Rep HD-128 (R nominee)",   level: "state",    party: "R", cash: 175816, raised: 102059, spent: 102143, asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Tom Butler") },
  { name: "Bo French",             office: "Texas Railroad Commissioner (R nominee)", level: "state", party: "R", cash: 79000, raised: 1400000, asOf: "May 2026", incumbent: false, filingUrl: TEC("Bo French") },
  // Federal 2026 nominees not yet in FEC system
  { name: "Dan Crenshaw",          office: "U.S. Rep CD-02 (lost R primary to Steve Toth, Mar 2026)", level: "federal", party: "R", cash: 843500, asOf: "Q4 2025", incumbent: true, filingUrl: FEC("H8TX02224") },
  { name: "Steve Toth",            office: "U.S. Rep CD-02 (R nominee)",     level: "federal",  party: "R", cash: 124318,    raised: 698325, spent: 574007, asOf: "Q1 2026", incumbent: false, filingUrl: FEC("H6TX08175") },
  { name: "Morgan Luttrell",      office: "U.S. Rep CD-08 (not seeking reelection. Open seat 2026)", level: "federal", party: "R", cash: 397000, asOf: "Q1 2026", incumbent: true, filingUrl: FEC("H2TX08226") },
  { name: "Jessica Steinmann",    office: "U.S. Rep CD-08 (R nominee)",     level: "federal",  party: "R", cash: 131136, raised: 1824372, spent: 1693236, loans: 650000, asOf: "Q1 2026", incumbent: false, filingUrl: FEC("H6TX08209") },
  { name: "Laura Jones",          office: "U.S. Rep CD-08 (D nominee)",     level: "federal",  party: "D", cash: 8836,  raised: 8836, asOf: "Q1 2026", incumbent: false },
  { name: "Troy Nehls",           office: "U.S. Rep CD-22 (not seeking reelection. Open seat 2026)", level: "federal", party: "R", cash: 186167, raised: 425954, spent: 528865, asOf: "Q1 2026", incumbent: true, filingUrl: FEC("H0TX22302") },
  { name: "Trever Nehls",         office: "U.S. Rep CD-22 (R nominee)",     level: "federal",  party: "R", cash: 36393, raised: 182538, spent: 146145, asOf: "Q1 2026", incumbent: false, filingUrl: FEC("H6TX22283") },
  { name: "Marquette Greene-Scott",office: "U.S. Rep CD-22 (D nominee)",   level: "federal",  party: "D", cash: 116,  raised: 41012, spent: 40531, asOf: "Apr 2026", incumbent: false, filingUrl: FEC("H4TX22197") },
  { name: "Brian Babin",          office: "U.S. Rep CD-36",                 level: "federal",  party: "R", cash: 930512, raised: 916868, spent: 632559, asOf: "Q1 2026", incumbent: true,  filingUrl: FEC("H6TX02079") },
  { name: "Rhonda Hart",          office: "U.S. Rep CD-36 (D nominee)",     level: "federal",  party: "D", cash: 3937,  raised: 6550,  asOf: "Q1 2026", incumbent: false, filingUrl: FEC("H4TX14111") },
  { name: "Ronald Dwayne Whitfield",office: "U.S. Rep CD-18 (R nominee)",  level: "federal",  party: "R", cash: 0,         asOf: "pending",  incumbent: false },
  { name: "Alexander Hale",        office: "U.S. Rep CD-07 (R nominee)",     level: "federal",  party: "R", cash: 6032,  raised: 61761, spent: 55729, loans: 3610, asOf: "May 2026", incumbent: false, filingUrl: FEC("H6TX07151") },
  { name: "Leticia Gutierrez",     office: "U.S. Rep CD-09 (D nominee)",     level: "federal",  party: "D", cash: 5962,  raised: 40024, spent: 34062, asOf: "Q1 2026", incumbent: false, filingUrl: FEC("H6TX09231") },
  { name: "Alex Mealer",           office: "U.S. Rep CD-09 (R nominee)",     level: "federal",  party: "R", cash: 414526, raised: 1770301, spent: 1355775, asOf: "May 2026", incumbent: false, filingUrl: FEC("H6TX09140") },
  { name: "Melissa McDonough",     office: "U.S. Rep CD-38 (D nominee)",     level: "federal",  party: "D", cash: 37302, raised: 47897, spent: 33294, asOf: "Apr 2026", incumbent: false },
  { name: "Jon Bonck",             office: "U.S. Rep CD-38 (R nominee)",     level: "federal",  party: "R", cash: 846000,    asOf: "Q1 2026",  incumbent: false, filingUrl: FEC("C00904151") },
  { name: "Martha Fierro",         office: "U.S. Rep CD-29 (R nominee)",     level: "federal",  party: "R", cash: 0,         asOf: "Dec 2025",  incumbent: false, filingUrl: FEC("H6TX29122") },
  // County
  { name: "Rodney Ellis",          office: "Commissioner PCT 1",             level: "county",   party: "D", cash: 7783681,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Rodney Ellis") },
  { name: "Lesley Briones",        office: "Commissioner PCT 4",             level: "county",   party: "D", cash: 4058292,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Lesley Briones") },
  { name: "Steve Radack",          office: "Commissioner PCT 4 (R nominee)", level: "county",   party: "R", cash: 410969.79,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+EzZBFseAp1uK35cp80QU8OPjPAWK0ZMceaq2xgb30uoa8hSsy54QptvWbpzYtqOKgLMfxqfKiMLGntpysWEDHqovYMQJhT1O14pmy/DBID" },
  { name: "Adrian Garcia",         office: "Commissioner PCT 2",             level: "county",   party: "D", cash: 2544776,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Adrian Garcia") },
  { name: "Tom Ramsey",            office: "Commissioner PCT 3",             level: "county",   party: "R", cash: 2032612,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Tom Ramsey") },
  { name: "Letitia Plummer",       office: "County Judge (D nominee)",       level: "county",   party: "D", cash: 420000,    asOf: "May 2026 est.", incumbent: false, filingUrl: TEC("Letitia Plummer") },
  { name: "Orlando Sanchez",       office: "County Judge (R nominee)",       level: "county",   party: "R", cash: 890000,    asOf: "May 2026 est.", incumbent: false, filingUrl: TEC("Orlando Sanchez") },
  { name: "Lina Hidalgo",          office: "County Judge (lame duck, not seeking reelection)", level: "county", party: "D", cash: 344873, asOf: "Jan 2026", incumbent: true, filingUrl: TEC("Lina Hidalgo") },
  { name: "Annise Parker",         office: "County Judge (lost D runoff)",   level: "county",   party: "D", cash: 332475,    asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Annise Parker") },
  { name: "Abbie Kamin",           office: "County Attorney",                level: "county",   party: "D", cash: 572019,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Abbie Kamin") },
  { name: "Warren Howell",         office: "County Judge (lost R runoff)",   level: "county",   party: "R", cash: 106156,    asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Warren Howell") },
  { name: "Ed Gonzalez",           office: "Sheriff",                        level: "county",   party: "D", cash: 90573,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Ed Gonzalez") },
  { name: "Richard Vega",          office: "Commissioner PCT 2 (R general)", level: "county",   party: "R", cash: 59395,     asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Richard Vega") },
  { name: "Marilyn Burgess",       office: "District Clerk (not seeking reelection)", level: "county", party: "D", cash: 26240, asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Marilyn Burgess") },
  { name: "Jose Maldonado",        office: "District Clerk (D nominee)",     level: "county",   party: "D", cash: 0,         asOf: "Jan 2026", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxwbTBaphgABqJKXPLS3XHQDX6EYcCTgv3dPNyXJFiJSapQcl/OA2Ash/C41v1qQaAaBNHi7cB8Uva5DCY3I0GBm/fXzup6c5t8YtW+SmoYBV" },
  { name: "Chris Daniel",          office: "District Clerk (R nominee)",     level: "county",   party: "R", cash: 12833,     asOf: "Jan 2026", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8M9YwwC9cd/fdbv3GNkxZ5Cag5PujIchS2Wr1Vb9gg26+9W6xT03AzTu/Q9GU5vioWOIWzQlnF4dvedcwxHpPA=" },
  { name: "Jacqueline Lucci Smith", office: "County Attorney (R nominee)",   level: "county",   party: "R", cash: 1708,      asOf: "Jan 2026", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=7ACcDpwDcJiOhbhvmdgtr4W1+Armkq+2iWhX7xkTj703TB9OD8+9bT2Ow5a9JviSsLmPnknjqTZWXECwyvU8IZdE5P5q6T/qv/+07omN2zXk40rDl9F8HiFapl4I5XqA" },
  { name: "Teneshia Hudspeth",     office: "County Clerk",                   level: "county",   party: "D", cash: 17147,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Teneshia Hudspeth") },
  { name: "Mike Wolfe",            office: "County Clerk (R nominee)",       level: "county",   party: "R", cash: 0,         asOf: "Jan 2026", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxxq1raj4KnYkpgvyBcZl2rsauMcTfrjxE1b2L02OcTm0XtGxGGJiVTOHZS4IxFK1C0YHaFzVmq1AP4ZHBwngsJKpSsNUQMVr9jxg9lbfzjuZ" },
  { name: "Sean Teare",            office: "District Attorney",              level: "county",   party: "D", cash: 14291,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Sean Teare") },
  { name: "Annette Ramirez",       office: "Tax Assessor-Collector",         level: "county",   party: "D", cash: 5775,      asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Annette Ramirez") },
  { name: "Carla Wyatt",           office: "County Treasurer",               level: "county",   party: "D", cash: 2128,      asOf: "Jul 2025", incumbent: true,  filingUrl: TEC("Carla Wyatt") },
  { name: "Marc Cowart",           office: "County Treasurer (R nominee)",   level: "county",   party: "R", cash: 0,         asOf: "Jan 2026", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxyogyWeN2yFtXcFh8/gBJj6SsMjcJl00T7XNWm02pPIgkEZlhSv/G+lswM9lnjUPLYi7vg4rC1gLaqCX79NMNT1W5qbbjG0UdfUTafHYouF3" },
  // Constables: file at ethics.harrisvotes.com
  { name: "Alan Rosen",            office: "Constable PCT 1",                level: "county",   party: "D", cash: 1710287,   asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox7fWG8AMVCN44IohFufLZe+L2IP8/uebm3r0G2r1vid9amdyVLLPRT/ES5ecSyOOjrl4q3S/aINjXV3+Lssq3QDt119DG11qTIC9VQm3jDmh" },
  { name: "Isabel G Garcia",       office: "Constable PCT 2",                level: "county",   party: "D", cash: 370,       asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxygdwgNEUqg+4IAHj3HXMTZ0fYjb38fjthZ7Df4j4N629YT+O8jOSAM1UWXR6LQ6fjEd469+y4zON54NaRhwVrbdDZOV8CWZyxgNQp91UHgG" },
  { name: "Sherman Eagleton",      office: "Constable PCT 3",                level: "county",   party: "D", cash: 61400,     asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox9UiK0ZER9VFZQmEbSr954Vxe5Ucw9lswpVizH8mi60zS9XdU6lA69qQJxvdmtBQG5m5eDTxQf+0wxSxrI35ghYD/yugGslYoyq+zSpYV1c7" },
  { name: "Mark Herman",           office: "Constable PCT 4",                level: "county",   party: "R", cash: 72641.77,  asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=G3bILfZhKXWRjwhrYUsk8VSfl7QegaGbMVmqrwyccwIVPgysJgt/MGGFBgMmGdNS80a5YLjH7M5mIOMh2zB1/Pjroxm9LXycBcSUAbSuXAuSPbzKuyW7G7FLxTa2EtWp" },
  { name: "Terry Allbritton",      office: "Constable PCT 5",                level: "county",   party: "R", cash: 63912,     asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox2ySEecG4r2+oQk2F9/m4wKp7Kp54GcJbsCVT+wCSE0HIi40pbCf+EVMa+1tM22Dd8BqvUK1FhezKZ5Nz6TVZoA=" },
  { name: "Silvia Trevino",        office: "Constable PCT 6",                level: "county",   party: "D", cash: 27785,     asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox3rwBpvXU2+UnLp5lqWcJoazjFDUckw6VldKLhmyuB7cXz9/aErUZmm5zgaIgvEm/osAId10RFC0DrQOnis0jBY=" },
  { name: "James Phillips",        office: "Constable PCT 7",                level: "county",   party: "D", cash: 29780,     asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox7cXUms76TpSrzveWiK0KaEI7LwLJvchYocrZH8iNj3l5x/dpXSo5xB9msFieEbkoNiIFTARvwercYAOh8lgAGTf2aU2fSdu1vzrJhU1mAMI" },
  { name: "Phil Sandlin",          office: "Constable PCT 8",                level: "county",   party: "R", cash: 48802,     asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox0yW/z9oYZ414D1OyvOg3QVr0E1xSZmUujeymfe6SOG8ulL2DDd/keTOzygm6ZEhshVjW+QJsYANagbxNqyKDoQ=" },
  // City of Houston
  { name: "John Whitmire",         office: "Mayor",                          level: "houston",  party: "D", cash: 2741969,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("John Whitmire") },
  { name: "Ed Pollard",             office: "City Council District J",        level: "houston",  party: "D", cash: 2197573,   asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Ed Pollard") },
  { name: "Willie Davis",          office: "City Council At-Large 2",        level: "houston",  party: "R", cash: 0,         asOf: "pending",  incumbent: true,  filingUrl: TEC("Willie Davis") },
  { name: "Chris Hollins",         office: "City Controller",                level: "houston",  party: "D", cash: 530765,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Chris Hollins") },
  { name: "Martha Castex-Tatum",   office: "City Council District K",        level: "houston",  party: "D", cash: 366298,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Martha Castex-Tatum") },
  { name: "Tiffany Thomas",        office: "City Council District F",        level: "houston",  party: "D", cash: 262877,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Tiffany Thomas") },
  { name: "Julian Ramirez",        office: "City Council At-Large 1",        level: "houston",  party: "R", cash: 174226,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Julian Ramirez") },
  { name: "Mario Castillo",        office: "City Council District H",        level: "houston",  party: "D", cash: 160561,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Mario Castillo") },
  { name: "Twila Carter",          office: "City Council At-Large 3",        level: "houston",  party: "R", cash: 103895,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Twila Carter") },
  { name: "Alejandra Salinas",     office: "City Council At-Large 4",        level: "houston",  party: "D", cash: 101659,    asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Alejandra Salinas") },
  { name: "Sallie Alcorn",         office: "City Council At-Large 5",        level: "houston",  party: "D", cash: 79344,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Sallie Alcorn") },
  { name: "Fred Flickinger",       office: "City Council District E",        level: "houston",  party: "R", cash: 60932,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Fred Flickinger") },
  { name: "Amy Peck",              office: "City Council District A",        level: "houston",  party: "R", cash: 44030,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Amy Peck") },
  { name: "Joaquin Martinez",      office: "City Council District I",        level: "houston",  party: "D", cash: 29304,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Joaquin Martinez") },
  { name: "Carolyn Evans-Shabazz", office: "City Council District D",        level: "houston",  party: "D", cash: 17235,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Carolyn Evans-Shabazz") },
  { name: "Tarsha Jackson",        office: "City Council District B",        level: "houston",  party: "D", cash: 9689,      asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Tarsha Jackson") },
  { name: "Joe Panzarella",        office: "City Council District C",        level: "houston",  party: "D", cash: 26342,     asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Joe Panzarella") },
  { name: "Mary Nan Huffman",      office: "City Council District G",        level: "houston",  party: "R", cash: 0,         asOf: "pending",  incumbent: true,  filingUrl: TEC("Mary Nan Huffman") },

  // Harris County Justice of the Peace: file at ethics.harrisvotes.com (same as commissioners)
  // Names verified from jp.hctx.net; cash populated by live HC scrape (page 4 of CFR PDF)
  { name: "Eric William Carter",   office: "Justice of the Peace PCT 1 PL 1", level: "county",   party: "D", cash: 202926, spent: 47741, asOf: "Dec 2025", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxxso6WMq1WeCb0BSKL/+IEV1o8bPfZPQFonSV7780FKGcuoV2vODDyXTjFrdWWDXBKWU47mAfyn2Eufy1Jsr2Ks=" },
  { name: "Steve Duble",           office: "Justice of the Peace PCT 1 PL 2", level: "county",   party: "D", cash: 68252.43, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox09KSF/aPnRRGy+vU95tiTemZ+5X21w5RLXEYrfvakBJhBWN5gcEuFyhm4JB+2CbX7kofdbNDvPZOFiq7y10FNA=" },
  { name: "Jo Ann Delgado",        office: "Justice of the Peace PCT 2 PL 1", level: "county",   party: "D", cash: 0, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxwX/PFMgO+SxK9XPP+LpcMRftwOdVjAe50Tbrxlmexn0iDGwSRqfiROg3fU0UAiB7/YobTBbnRAYnfhQ6dOAlzE=" },
  { name: "Dolores Lozano",        office: "Justice of the Peace PCT 2 PL 2", level: "county",   party: "D", cash: 95415.62, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxzqyvmT400PN3NkdR0hy+dONeETHeuSPot7O2OYef8eKIRfJ2PCwdcWqE1Y2Ybf5PZq7xE+uKIsYLHzslFQJBTn8qyDIAQFDb0aDKD//m9r0" },
  { name: "Jack Ezell",            office: "Justice of the Peace PCT 2 PL 2 (R nominee)", level: "county", party: "R", cash: 250, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox5BlFVFJn8vh6QJNM/iCmFFUc38h0D+8TkSrGP8TOIoaGdLLrDn6GU/a7iLJtmuoUHmgkY5pWSiAhaKd1WVjKyk=" },
  { name: "Joe Stephens",          office: "Justice of the Peace PCT 3 PL 1", level: "county",   party: "D", cash: 28399, raised: 23975, spent: 14017, asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox6t7eQU3M+9Fl87NEOkBnHgCwYxpeUvnrvock9c0/pg+on9O7GPDo8sxlf3ArI0ZpFaLEnmk61Pn2WA0tCAdDkqp5rSuLldsBlCMAnJCxtPM" },
  { name: "Lucia Bates",           office: "Justice of the Peace PCT 3 PL 2", level: "county",   party: "D", cash: 23928.07, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxzpeM9tGr+2wNn/sZbiEz4UVfBUuo8qaOqIO4ohx9DkAFpK0+2XcU/quVXIuG7KXOcmmZHXUBpAjD/MhRtZd3G6hnvhHFjsBYfR5IEnXXzFK" },
  { name: "Lincoln Goodwin",       office: "Justice of the Peace PCT 4 PL 1", level: "county",   party: "D", cash: 1658, asOf: "Dec 2025", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox0dw3h3Y1bSOVxW+NqMn7HDRLpom2XjGN120lofrRUeC6rY2DaInsFPMnE285AerRhCfy5QPrG+Q2peZ/3Xk58/YwD5qutrEd06bY/Xzl31w" },
  { name: "Laryssa Korduba",       office: "Justice of the Peace PCT 4 PL 2", level: "county",   party: "D", cash: 102371.40, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxwe0ff8r3Volw9i96y3LHmRLp7X1LUUJ5hU/j00nV4XaS1gw6uHH61ilUO+hprOYxClj9wJc1LByv6ANGJNS8e8=" },
  { name: "James Lombardino",      office: "Justice of the Peace PCT 5 PL 1", level: "county",   party: "R", cash: 0, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxysOqGqjqv8TRUSpfYSNtOry2D8L30sftel38/kwUqvu4SSxQyopwU8/z8XawYnCUQ0F/9OIPMZxx9Fd2llcGhw=" },
  { name: "Bob Wolfe",             office: "JP PCT 5 PL 2 (current; lost R primary to Mark Fury)", level: "county", party: "R", cash: 22971, asOf: "Dec 2025", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8U3JkNl/Ny6JrjxT7lChrotb+T434XbnUMw+fr0DF5ke/bvQ8HB/H77wRJZDQwSRDl/VdYKw/4Kxve8kVmHL2ii4CXfjRvmX6/7Bt98BF99" },
  { name: "Mark Fury",             office: "Justice of the Peace PCT 5 PL 2 (R nominee)",    level: "county", party: "R", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox1D+QI7IHQafhwUUsGw39/Vp1xF4x113iZuBjGpS7POtwprrEBPDqV91sM3PT/uOycOrF/E8hPhVYLL0BdaKIWMHhCYET+byEl/8vpubSQn2" },
  { name: "Lisa Jefferson",        office: "Justice of the Peace PCT 5 PL 2 (D nominee)",    level: "county", party: "D", cash: 2400, asOf: "Dec 2025", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8CVE9O8TE0UA2w0aFdgHGcPMSmjzp2abfSsRqNg+xBiy+E/ObG1ngzhlNoRBcCR+lWf6q2AUmZivoQVe2N8n2xk1/JRHahZfpMXgd8Z3DEj" },
  { name: "Victor Treviño III",    office: "Justice of the Peace PCT 6 PL 1",                level: "county", party: "D", cash: 5773.85, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8uTNTE4/ZE/lSGcTXCH9UcF/5F1EgFQq0i9XxFxI1Htqq5PslFksba8MslbxHN15xwp0PvGKx6r77tUbtFP5MWt6oFBnRA/3rzCyYpj789/" },
  { name: "Angela D. Rodriguez",   office: "Justice of the Peace PCT 6 PL 2", level: "county",   party: "D", cash: 30, spent: 46644, asOf: "Dec 2025", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxwk0pXFi1Un/zBNEmPeyRwx1YLtZlg2JXeMDd2p9Q2993IvLhnPQht/xb/p7lmiQgzkV+YH+m7ECm1WzWzUVLqzfLvgyWEvCgvXEdqrNyo37" },
  { name: "Wanda E. Adams",        office: "Justice of the Peace PCT 7 PL 1", level: "county",   party: "D", cash: 2500, raised: 2500, asOf: "Dec 2025", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox4RQvEN7aqJzO0fTKvIiv3bnk7WW3GouXBjIN9t0+nTCe2tW1qvR3XIZyqyha0v/D819fyr5v0CNpXiYs6Kex/9zR5TaINjtAiKqoZPoUCHU" },
  { name: "Sharon M. Burney",      office: "JP PCT 7 PL 2 (lost D runoff to Melanie Miles)", level: "county", party: "D", cash: 0, loans: 40000, asOf: "2026-04-30", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxxcB+tQWUsa3kR3G+syQnX7lN51A0w1dT/z3ugt0t0UVLppJknqTRbMUPnrcnXeH8xJw/knojFD92Qjt5G6SAYIiAyvJ3+wGGitTWp4vqcbZ" },
  { name: "Melanie Miles",         office: "Justice of the Peace PCT 7 PL 2 (D nominee)",    level: "county", party: "D", cash: 27287.78, asOf: "2026-04-27", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox1UlWoXs+f78czkR34LDpHgxEeLV/ojxqDPafb5pnbSn3N3wIHQN+PfVXIVFupC2KmY8eF8W7BPSUaP55S4WyDNv0bfNU/CQYCBQMt+qphZI" },
  { name: "Holly Williamson",      office: "Justice of the Peace PCT 8 PL 1", level: "county",   party: "R", cash: 86153, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox4BrQJydyHe2+oSWPt6A95zl61apfDFGKyJFWN7x1ZnX/sYkU1drTjWQmI7J5iCE3Ex2uCBaaJYXI7VbZLTjx8A=" },
  { name: "Louie Ditta",           office: "Justice of the Peace PCT 8 PL 2", level: "county",   party: "R", cash: 98946.31, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxzEYN25RaGbKu2HX6+uNm/gRAD1gw3z3vJhTxMI7HrQEg56sjj9xbCzSUbNhXa26vTNcgBSRA1Y53pk70bi0+4o3Tk03DfJgKslhMfYz+e07" },

  // Harris County Probate Courts: file at ethics.harrisvotes.com
  { name: "Jerry Simoneaux",     office: "Probate Court No. 1",                    level: "county",   party: "D", cash: 36038,  asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+PlgXKyhSrV0Wh9B1n8NjBI6HhN1nSBwcFAsUurIYtAPx2f70BPvdE/TJ4OXOGJ75KRtDJWPQ4hl20xYHJWkNU=" },
  { name: "Loyd Wright",         office: "Probate Court No. 1 (R nominee)",        level: "county",   party: "R", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8KjvtVLRetVvgrQERAsN458grbaQhsTInbP+bVudoVLPUfte4QtAIYbhTJMW93bkIpVZJT7XspHKAUjReoOquizOvNEmWIybRWjd2NPtw8y" },
  { name: "Pamela Medina",       office: "Probate Court No. 2",                    level: "county",   party: "D", cash: 128463, asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+QUY/s0Sn7hHDz3/2zFhmsCJiVufNWuO9y43Zpj+n8xsIEjxJOV09AuEDbR2V0DBz7JrXRYkBIbingbjS34EWs=" },
  { name: "Paul Shanklin",       office: "Probate Court No. 2 (R nominee)",        level: "county",   party: "R", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox4X2DJx9Nkzn1gEPEGkiHCxwNampcuSYIosYEMK/HmAkOghz9WjRptYTD+6iYCB/P+cCK2DoV1BKr1wXj/gk+XA=" },
  { name: "Jason Cox",           office: "Probate Court No. 3",                    level: "county",   party: "D", cash: 81072.40, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxzbcdkAZ8emxC3w3CDRPKrAtSSBhPtscoH11lb6TC0yTmzX6ojWDmdLsKfvL675aoghxt1o7mGJlhPI2AldUYXM=" },
  { name: "Ronald Schramm",      office: "Probate Court No. 3 (R nominee)",        level: "county",   party: "R", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxw1db8nl7KF17W9Tu2V/KpneaXsPIVpC5BQDwWBZWfp0rgOSWDP/r7IIWk1LOIbul+/ILUlJXCi48LHdmXde+as=" },
  { name: "James Horwitz",       office: "Probate Court No. 4",                    level: "county",   party: "D", cash: 66096,  asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxxQ8rGlR6SS/BASXjegBoXhhg0078C/5wjvvnIjeyeeExN0uakQnxvdOCv9xSFls0S8tg9ReRWTDLnG8Kj3ty1I=" },
  { name: "Kevin Fulton",        office: "Probate Court No. 4 (R nominee)",        level: "county",   party: "R", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox9cTR5Q4IO7KOd7n3dMUsu9L7Hi+JzjSEdljjEhNZzXFUDZY9WYvtluEe53QmJ3Cuk34faXVfZ70IGUVoRI5QQcuq9ULDCRlgNEVuj1ckoOg" },
  // Harris County Criminal Courts at Law judges: file at ethics.harrisvotes.com
  { name: "Alex Salgado",          office: "Criminal Court at Law No. 1",      level: "county",   party: "D", cash: 4455,   asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox04EQdnnD1kVhAXGdJEQYeA2wZblPxT/3ZoRtcra82vt+wdXXbV+FlyT7sHUJSbCAhONNF7PBHzHkvSXRUQLaE0=" },
  { name: "Paula Goodhart",        office: "Criminal Court at Law No. 2 (not seeking reelection)", level: "county", party: "D", cash: 0, asOf: "2025-12-31", incumbent: true, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox27qZW7JUzjvUKSE4O6SXepwx1fmICCxwWc+kZTmF5DAhzXJ7I1tDNCgnD0U14JTHmAE/loJB6ObftyQbHSfAXI=" },
  { name: "Matthew Ruben Perez",   office: "Criminal Court at Law No. 2 (D nominee)", level: "county", party: "D", cash: 0, asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox/oRS1wZPYSeSPJwwu4q9ttTQjZj6XAWY5Dsg/9bQmrW97PjolodfU5evbrtL3SSL0PifCjFYOSoxjgsdM4IyCs=" },
  { name: "Leslie R. Johnson",     office: "Criminal Court at Law No. 3",      level: "county",   party: "R", cash: 1000, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox9UPz59lyVM1tDbBl/cok8CBIuGGNC1Y6y3A9N0gvAcNooW//HK3598u/Yvs3y38KdzHMCnwPflutrm3t0Z8Nig=" },
  { name: "Shannon Baldwin",       office: "Criminal Court at Law No. 4",      level: "county",   party: "D", cash: 4975.91, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox42zQyItjt7LVki6YsyAnHKXmauNa7+gd1HnmfJx6yxiEAXpSkJcRQ68ep6n9ubXJI+/J9/fcABlOoDNNQRWpR7dQv1iewVztgbpNw9iCJcV" },
  { name: "David Fleischer",       office: "Criminal Court at Law No. 5",      level: "county",   party: "D", cash: 3460,   asOf: "Jan 2026", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox5DdJ/GpYf4k9Vjn/D+f0rBkoqagRe+ydZAPncrR+HvuwOoKoA01fcb9+xXi4KJX73Z+kL2ZT4AQ5Gcd9MWmoRw=" },
  { name: "Kelley Andrews",        office: "Criminal Court at Law No. 6",      level: "county",   party: "D", cash: 8757.08, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox6adQjmbJvXGnxyKDBFIzpi30r+kwDnFbSG6d0G+k+ElHWBS3GHZIvcJwWUd4DdM7zn7jaWCuNn6bvCiBMZ/Ts4=" },
  { name: "Andrew Wright",         office: "Criminal Court at Law No. 7",      level: "county",   party: "D", cash: 4764.84,   asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox8U0bHJkmJoBeGFF4Pd6hl8fiIWYeCtxrxNexei8zUOiCwW+iuHGeom5G3cXounAyovBccZiPhN703FzGLKiZCk=" },
  { name: "Erika Ramirez",         office: "Criminal Court at Law No. 8",      level: "county",   party: "D", cash: 24898.43,  asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox3zaAl7JzN0dfVCFCrPPF9DUSd2aU2Qwoq9pFIPikxguviFZR2qerjdQcCzzywYzR5eqkorlOg+u/wh/vgx7rQY=" },
  { name: "Toria J. Finch",        office: "Criminal Court at Law No. 9",      level: "county",   party: "D", cash: 12508.47,  asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox2V9smpVn1rdXU+7MrpGUhc92FJjdg2fU2dAmRCSK3z6kAF5e6iTJGVL/hAb4KLBF24w2GbpPaUtmHwbuR/1xCz3eHj2SycgMxOmj5DEFEbf" },
  { name: "Juanita Jackson",       office: "Criminal Court at Law No. 10",     level: "county",   party: "D", cash: 4289.29,   asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxwEnLxJgym+HO1FoWNf1nZwA3v2rRuD7mS0B4TqReXp4ww6DtX9Z7y6LmO9roovHqtRR27ljQNiW86BHPZnQE+dNzcODPlVASKtRLzUDoI5m" },
  { name: "Sedrick T. Walker II",  office: "Criminal Court at Law No. 11",     level: "county",   party: "D", cash: 6322.79,   asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox83f/nEIWYHofhP55BxhM5Y1tQeWJbRJyQUZvalRvLMIdkmn68mQHiNG3lKT2AGpDxZyCFiKX28xSbrz2wjGhzshKXxYeJQcf+1eCb2WcoFa" },
  { name: "Ashley Mayes Guice",    office: "Criminal Court at Law No. 12",     level: "county",   party: "D", cash: 4127,      asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxxU+pNKByLHWZcRk1/XIJCcPBFDivC+Jf04BosaV5m7Kw4hVBm0v8J9lN99FxINHBwp31bU/ktQFMN6ktpGXVoJ3QPzG1U+FgqDhCah/wJLO" },
  { name: "Raul Rodriguez",        office: "Criminal Court at Law No. 13",     level: "county",   party: "D", cash: 22775.24,  asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox1qlGVyFp6HkC6uYyVeSCiryLhTUzLk6rfvfSqT5xxB9ROEjfaI2gc73XupwbT4IWOQ/UrXTbOaH5f+cQcQDT4o=" },
  { name: "Jessica N. Padilla",    office: "Criminal Court at Law No. 14",     level: "county",   party: "R", cash: 5568, asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxyS/x1yovE4EB1qpC92BctCTwx93HIFr8K1e2tiO9UtoeJsUt+pwQw6+4nWQhh2ZVOBNNu1d7xsCLwAEtQT/YlA=" },
  { name: "Yahaira Quezada",       office: "Criminal Court at Law No. 14 (D nominee)", level: "county", party: "D", cash: 5459.07,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxyw4WVUPWoad3pS7SkgqViX6TVlIKBZaD0N2EiISEvrfVpYtD4AMBGN5DP3IAV5VTgCNBXF3BoA+kqFZsiQY3vU=" },
  { name: "Tonya Jones",           office: "Criminal Court at Law No. 15",     level: "county",   party: "D", cash: 17250,     asOf: "2025-12-31", incumbent: true,  filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox1c/cUehiab98eME0b7sTas/8ZGWkG/aS3vR/4+S5JoFiQ30nglu+HWmM61ms4ovThLFM7AfzXmw2oM6fIiztklar8ieTvUTGHd0ktrOjj4y" },
  // CCL R nominees. All file at ethics.harrisvotes.com
  { name: "Erin Swanson",          office: "Criminal Court at Law No. 1 (R nominee)",  level: "county",   party: "R", cash: 8735.85,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+Zu06XUpQb6GZbGsYw/4rUAiNu81l2J8yKYkl3k/+wzGMc6ROmXDJeEdcck8ssprjcCgNizBTv5ufZs2hEbPSJaBLChoOWRKbPQzVEmD7ow" },
  { name: "Matt Alford",           office: "Criminal Court at Law No. 2 (R nominee)",  level: "county",   party: "R", cash: 0,        asOf: "2025-07-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=G3bILfZhKXWRjwhrYUsk8S0DpEXO+d26hEMnx4zIzKRi2L1AVN7Y9Jff33FD2H+AOaNy3hPMwMuOb2F5huFv/p2EkrZ7+4xZ6ZDBkZIEJTtskyLgMgIxmDDw1fid7mj1" },
  { name: "Allison Mathis",        office: "Criminal Court at Law No. 3 (D nominee)",  level: "county",   party: "D", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=G3bILfZhKXWRjwhrYUsk8d4egjiJv4N96rhe+MZz2MJXRMkUHlwBRyg8ktHLtD3uMRRtJDUGfgqI9gqzs7eeaogBIC1HcnbdLBqzBVe3++PxzNO6mW6nkLo0lLdC5evX" },
  { name: "Rebecca Phillips Aceto", office: "Criminal Court at Law No. 4 (R nominee)", level: "county",   party: "R", cash: 6920.18,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6SqmckoxyA7GrK0IYFsnv5a3DEPdHR5DHdl2kJwAPRNDhc3kCgaTRBAASTJCTxZyMdSw1wwunZumGSjAvO3x6dmqMZstiw=" },
  { name: "Stella Stevens",        office: "Criminal Court at Law No. 5 (R nominee)",  level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+5W85adX9ml0kJOkn91QK9OBV2pMtIgCOUQAa9m9MPD9TChcN1CvdgTh3VPUEe1QyPzH9TIt2JQhsg6qLEZl5Q=" },
  { name: "Josh Normand",          office: "Criminal Court at Law No. 6 (R nominee)",  level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox9ocUXk3ifPXsLSDsH0xpuyVm2O2YHF5I7uS9xFFCBwcv2CZEAVa25Rv5QANDooqR/hegEji8ey8asdk+swzIoK+iYg+VoNgcsspQfyUafe3" },
  { name: "Thomas Brodrick",       office: "Criminal Court at Law No. 7 (R nominee)",  level: "county",   party: "R", cash: 5.15,     asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox08pxlF1L26s3YzQ7IBP6LMh9AJMAY0ydgkuwLn8cqhnmlZpjsie7uNUl93vOm3B+Hzc0vhUaNt9ZXZiRTcX8pk=" },
  { name: "Victor Flores",         office: "Criminal Court at Law No. 8 (R nominee)",  level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox9Prft9FJPmmDA+KHiuoNU7rA6xD6oB7jxjpIC4x5VuH3A6b8f9QJgpbSBuLQhIGRPDQ1uvPdsO93Xyx1LQHApY=" },
  { name: "Xavier Alfaro",         office: "Criminal Court at Law No. 9 (R nominee)",  level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox6Uype5ukKR24smA73bLNcdpU2TZnmZf+iRTO1oJk+ycl+7Kr2tP4XZqi3xiysCQG1jWVDskHHO8LZESEuw7D/Y=" },
  { name: "Bao Hoang",             office: "Criminal Court at Law No. 10 (R nominee)", level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox1Z7YXiC0eiA8zaAtaMV9/anhhCNNKLlUr3Zo5Dlqfzdl4jpr3P5hw48P7arKnNwCqBJDIxNOBQc2WZykB+AKNWycOxZxcKB4cTsqJ2jb3wk" },
  { name: "Liz Buss",              office: "Criminal Court at Law No. 11 (R nominee)", level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox+Yu2vhyYBmtoM5Kf0qsvKIufX+cfoTCQew7BbD7x1cg1+a66i9+InJD+VbBy+exlPgELyN4EuNB5QnPy31Rs/E=" },
  { name: "Anna Emmons",           office: "Criminal Court at Law No. 12 (R nominee)", level: "county",   party: "R", cash: 9023.73,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox3+c/H0zmc05OZMs2o+FFUfynJkQrjyvVGM1X59Dol/yQON4AgAFsqxV+LVRTr7IfmLx0Pq75r8fOUnloY85V8s=" },
  { name: "Amber Cox",             office: "Criminal Court at Law No. 13 (R nominee)", level: "county",   party: "R", cash: 0,        asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckoxws88EOUg2nSiD3gqEBBWEE0dcbalQVzOU6HnHUvnuMYgczm+ElNjH+LDFPBu1Kui4RXYjOS0aE6174BvG31Sg0otygGMPlZvo2TK2ftyeeF" },
  { name: "Stephen St. Martin",    office: "Criminal Court at Law No. 15 (R nominee)", level: "county",   party: "R", cash: 2847.09,  asOf: "2025-12-31", incumbent: false, filingUrl: "https://ethics.harrisvotes.com/Document.aspx?ID=8clm5/UZ7yw9/6Sqmckox3TmKQ2s9d96Mnk5r4nmg2TTXcoSQe/xTaduTGl7uXfIstYhZn85TC4Zk7feQDaY5bYedvrgp8W18foZwZIXRH0=" },
  // Harris County Criminal District Courts (Felony. File with TEC as state court judges)
  { name: "Danilo Lacayo",         office: "182nd District Court",             level: "county",   party: "D", cash: 19178,  raised: 26753, spent: 5382,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Danilo Lacayo") },
  { name: "Lance Long",            office: "183rd District Court",             level: "county",   party: "R", cash: 444,    raised: 500,   spent: 105,    asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lance Long") },
  { name: "Beverly Armstrong",     office: "208th District Court",             level: "county",   party: "D", cash: 40723,  raised: 21910, spent: 20407,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Beverly Armstrong") },
  { name: "Caroline Dozier",       office: "228th District Court",             level: "county",   party: "R", cash: 24133,  raised: 600,   spent: 73,     asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Caroline Dozier") },
  { name: "Alyson Almaguer",       office: "228th District Court (D nominee)", level: "county",   party: "D", cash: 2032,   raised: 2000,  spent: 2623,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Alyson Almaguer") },
  { name: "Chris Morton",          office: "230th District Court",             level: "county",   party: "D", cash: 5269,   raised: 0,     spent: 2500,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Chris Morton") },
  { name: "Josh Hill",             office: "232nd District Court",             level: "county",   party: "D", cash: 11385,  raised: 5150,  spent: 6370,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Josh Hill") },
  { name: "Hilary Unger",          office: "248th District Court",             level: "county",   party: "D", cash: 19170,  raised: 23550, spent: 13963,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Hilary Unger") },
  { name: "Lori Chambers Gray",    office: "262nd District Court",             level: "county",   party: "D", cash: 15108,  raised: 22225, spent: 22061,  asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lori Chambers Gray") },
  { name: "Megan Long",            office: "230th District Court (R nominee)", level: "county",   party: "R", cash: 7525,   raised: 5000,  spent: 0,      loans: 2525, asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Megan Long") },
  { name: "Melissa Morris",        office: "263rd District Court",             level: "county",   party: "D", cash: 20694,  asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("Melissa Morris") },
  { name: "Veronica Nelson",       office: "482nd District Court",             level: "county",   party: "D", cash: 63952,  raised: 54518, spent: 5444,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Veronica Nelson") },
  { name: "Lori DeAngelo",         office: "495th District Court",             level: "county",   party: "R", cash: 28719,  raised: 31981, spent: 5467,   asOf: "Dec 2025", incumbent: true,  filingUrl: TEC("Lori DeAngelo") },
  { name: "Tiffany Hill",          office: "495th District Court (D nominee)", level: "county",   party: "D", cash: 2898,   raised: 3000,  spent: 1505,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Tiffany Hill") },
  // DC incumbents not seeking reelection: file with TEC
  { name: "DaSean Jones",       office: "180th District Court (not seeking reelection)", level: "county",  party: "D", cash: 46583, asOf: "Jan 2026", incumbent: true,  filingUrl: TEC("DaSean Jones") },
  { name: "Abigail Anastasio",  office: "184th District Court (not seeking reelection)", level: "county",  party: "D", cash: 0, asOf: "pending", incumbent: true,  filingUrl: TEC("Abigail Anastasio") },
  { name: "Jason Luong",        office: "185th District Court (not seeking reelection)", level: "county",  party: "D", cash: 0, asOf: "pending", incumbent: true,  filingUrl: TEC("Jason Luong") },
  // DC court nominees (non-incumbents)
  { name: "Brent Haynes",          office: "182nd District Court (R nominee)", level: "county",   party: "R", cash: 0,     asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Brent Haynes") },
  { name: "Tami Pierce",           office: "180th District Court (R nominee)", level: "county",   party: "R", cash: 6222,  raised: 3400,  spent: 2036,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Tami Pierce") },
  { name: "Stephanie Morales",     office: "180th District Court (D nominee)", level: "county",   party: "D", cash: 0,      asOf: "Jan 2026", incumbent: false, filingUrl: TEC("Nora Stephanie Morales") },
  { name: "Julia Maldonado",       office: "183rd District Court (D nominee)", level: "county",   party: "D", cash: 18255,  raised: 9538,  spent: 11087,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Julia Maldonado") },
  { name: "Heather Hudson",         office: "184th District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 0,     spent: 590,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Heather Hudson") },
  { name: "Katherine Thomas",      office: "184th District Court (D nominee)", level: "county",   party: "D", cash: 150569, raised: 64062, spent: 11492,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Katherine Thomas") },
  { name: "Mark Goldberg",         office: "185th District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 2500,  spent: 2500,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Mark Goldberg") },
  { name: "Andrea Beall",          office: "185th District Court (D nominee)", level: "county",   party: "D", cash: 40024,  raised: 6600,  spent: 2943,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Andrea Beall") },
  { name: "Stephen Driver",        office: "208th District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 0,     spent: 2962,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Stephen Driver") },
  { name: "Tony Coveny",           office: "209th District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 2500,  spent: 0,      asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Tony Coveny") },
  { name: "Robert Johnson",        office: "209th District Court (D nominee)", level: "county",   party: "D", cash: 26491,  raised: 0,     spent: 10869,  asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Robert Johnson") },
  { name: "Chuck Silverman",       office: "232nd District Court (R nominee)", level: "county",   party: "R", cash: 13531,  raised: 0,     spent: 5800,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Chuck Silverman") },
  { name: "David Overhuls",        office: "248th District Court (R nominee)", level: "county",   party: "R", cash: 11437,  raised: 8050,  spent: 2930,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("David Overhuls") },
  { name: "Nathan Moss",           office: "262nd District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 0,     spent: 500,    asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Nathan Moss") },
  { name: "Jason Campo",           office: "263rd District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 0,     spent: 2500,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Jason Campo") },
  { name: "Bryan Honeycutt",       office: "482nd District Court (R nominee)", level: "county",   party: "R", cash: 0,      raised: 0,     spent: 3380,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Bryan Honeycutt") },
  { name: "Michael Abner",         office: "496th District Court (D nominee)", level: "county",   party: "D", cash: 931,    raised: 5850,  spent: 4919,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Michael Abner") },
  { name: "Dan Simons",            office: "496th District Court (R nominee)", level: "county",   party: "R", cash: 21874,  raised: 21326, spent: 4035,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Dan Simons") },
  { name: "Peyton Peebles",        office: "497th District Court (R nominee)", level: "county",   party: "R", cash: 26964,  raised: 15075, spent: 1802,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Peyton Peebles") },
  { name: "Breanna Schwartz",      office: "497th District Court (D nominee)", level: "county",   party: "D", cash: 266,    raised: 266,   spent: 2500,   asOf: "Dec 2025", incumbent: false, filingUrl: TEC("Breanna Schwartz") },
];

// Merge pipeline-generated data (from `npm run finance-publish`) over the static
// baseline. Generated records only win when they carry a non-zero cash value so
// a failed pipeline run never wipes out good static data.
const generated = (generatedRaw as { candidates?: Array<Partial<CandidateFinance> & { name: string }> }).candidates ?? [];
const generatedByName = new Map(generated.map(r => [r.name.toLowerCase(), r]));

export const FINANCE_DATA_MERGED: CandidateFinance[] = FINANCE_DATA.map(d => {
  const gen = generatedByName.get(d.name.toLowerCase());
  if (!gen || !(gen.cash != null && gen.cash > 0)) return d;
  return {
    ...d,
    cash:   gen.cash   ?? d.cash,
    raised: gen.raised ?? d.raised,
    spent:  gen.spent  ?? d.spent,
    loans:  (gen as { loans?: number }).loans ?? d.loans,
    asOf:   (gen as { asOf?: string }).asOf   ?? d.asOf,
  };
});

export function getFinanceByName(name: string): CandidateFinance | null {
  const normalized = name.trim().toLowerCase();
  return (
    FINANCE_DATA_MERGED.find((d) => d.name.toLowerCase() === normalized) ?? null
  );
}

export function fmt(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${Math.round(n / 1000).toLocaleString()}K`;
  return `$${n.toLocaleString()}`;
}
