export type Category = "Elections" | "Legislature" | "Courts" | "City Council" | "HISD" | "Civic";

export interface CivicEvent {
  id: string;
  title: string;
  date: string;
  endDate?: string;
  category: Category;
  description: string;
  importance: "high" | "normal";
  location?: { lat: number; lng: number; address: string };
}

export const CAT_COLOR: Record<Category, string> = {
  Elections:     "#2563a8",
  Legislature:   "#7c3aed",
  Courts:        "#d97706",
  "City Council":"#0d9488",
  HISD:          "#dc2626",
  Civic:         "#16a34a",
};

export const EVENTS: CivicEvent[] = [
  // ── Elections ──────────────────────────────────────────────────────────
  { id: "vreg-primary-2026",  title: "Voter Registration Deadline. Primary",   date: "2026-02-02", category: "Elections", description: "Last day to register or update registration for the March 2026 Texas Primary Election.", importance: "high" },
  { id: "ev-primary-2026",    title: "Early Voting. 2026 Texas Primary",       date: "2026-02-17", endDate: "2026-02-28", category: "Elections", description: "Early voting period for the March 3 Texas Primary. Harris County Clerk locations open across the county.", importance: "high" },
  { id: "primary-2026",       title: "2026 Texas Primary Election Day",          date: "2026-03-03", category: "Elections", description: "Texas statewide primary election. Vote for nominees for U.S. Senate, Congress, Governor, state legislature, and Harris County offices.", importance: "high" },
  { id: "primary-runoff-vreg-2026", title: "Voter Reg Deadline. Primary Runoff", date: "2026-04-27", category: "Elections", description: "Last day to register to vote for the May 2026 Primary Runoff.", importance: "normal" },
  { id: "ev-runoff-2026",     title: "Early Voting. 2026 Primary Runoff",      date: "2026-05-11", endDate: "2026-05-22", category: "Elections", description: "Early voting period for the May 26 Primary Runoff.", importance: "normal" },
  { id: "runoff-2026",        title: "2026 Texas Primary Runoff",                date: "2026-05-26", category: "Elections", description: "Primary runoff for races where no candidate cleared 50% in March.", importance: "high" },
  { id: "vreg-general-2026",  title: "Voter Registration Deadline. General",   date: "2026-10-05", category: "Elections", description: "Last day to register to vote for the November 3, 2026 General Election.", importance: "high" },
  { id: "ev-general-2026",    title: "Early Voting. 2026 General Election",    date: "2026-10-19", endDate: "2026-10-30", category: "Elections", description: "Early voting period for the November 3 General Election.", importance: "high" },
  { id: "general-2026",       title: "2026 General Election Day",                date: "2026-11-03", category: "Elections", description: "Texas General Election. Polls open 7 AM–7 PM.", importance: "high" },
  // ── Legislature ──────────────────────────────────────────────────────────
  { id: "lege-89-adjourn",    title: "TX 89th Legislature Adjourned",            date: "2025-06-02", category: "Legislature", description: "The Texas 89th Regular Session concluded. Next regular session begins January 2027.", importance: "normal" },
  { id: "lege-90-start",      title: "TX 90th Legislature Convenes",             date: "2027-01-12", category: "Legislature", description: "The 90th Texas Regular Legislative Session begins. Sessions meet every odd year, January through June.", importance: "high" },
  { id: "lege-shhs-jul7-26",  title: "Senate Health & Human Services Interim Hearing", date: "2026-07-07", category: "Legislature", description: "Senate HHS Committee hears interim charges on THC product health impacts, mental health crisis/homelessness services, and Texas Child Mental Health Care Consortium oversight. Sens. Alvarado and Kolkhorst sit on this committee.", importance: "normal" },
  { id: "lege-shhs-jul8-26",  title: "Senate Health & Human Services Interim Hearing", date: "2026-07-08", category: "Legislature", description: "Senate HHS Committee hears interim charges on exploitation in the surrogacy/fertility industry and DFPS registry/emergency-preparedness implementation. Sens. Alvarado and Kolkhorst sit on this committee.", importance: "normal" },
  { id: "lege-sfin-jul27-26", title: "Senate Finance Committee Interim Hearing", date: "2026-07-27", endDate: "2026-07-28", category: "Legislature", description: "Senate Finance Committee hears interim charges on expanding the homestead exemption, lowering the senior exemption age from 65, transportation funding needs, higher-education financial transparency/audit adequacy, and preventing fraud, waste, and abuse in state agency spending. Sens. Alvarado, Bettencourt, and Huffman sit on this committee.", importance: "normal" },
  { id: "lege-shied-jul28-26", title: "Senate Higher Education Committee Interim Hearing", date: "2026-07-28", endDate: "2026-07-29", category: "Legislature", description: "Senate Higher Education Committee monitors implementation of SB 37 (university governance/curriculum review) and HB 127 (barring foreign-adversary ties at Texas institutions), and examines the Public Junior College State Finance Program funding formula that sets state aid to Houston Community College and Lone Star College.", importance: "normal" },
  { id: "lege-sbc-jul29-26",  title: "Senate Business & Commerce Interim Hearing", date: "2026-07-29", category: "Legislature", description: "Senate Business & Commerce Committee hears interim charges on ERCOT grid capacity/transmission buildout and AI data centers' impact on power, water, and property rights. Sens. Cook and Kolkhorst sit on this committee.", importance: "normal" },
  { id: "lege-snred-aug11-26", title: "Senate Natural Resources & Econ. Dev. Interim Hearing", date: "2026-08-11", category: "Legislature", description: "Senate Natural Resources & Economic Development Committee hears interim charges on water demand from data centers/new industries versus farmers and ranchers, and wildfire risk/suppression capacity. Sens. Miles and Middleton sit on this committee.", importance: "normal" },
  // ── Harris County Commissioners Court ───────────────────────────────────
  { id: "cc-jul-1",  title: "Commissioners Court Meeting", date: "2025-07-08",  category: "Courts", description: "Harris County Commissioners Court regular meeting. Agenda posted 72 hours prior at harriscountytx.gov.", importance: "normal" },
  { id: "cc-jul-2",  title: "Commissioners Court Meeting", date: "2025-07-22",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-aug-1",  title: "Commissioners Court Meeting", date: "2025-08-12",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-aug-2",  title: "Commissioners Court Meeting", date: "2025-08-26",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-sep-1",  title: "Commissioners Court Meeting", date: "2025-09-09",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-sep-2",  title: "Commissioners Court Meeting", date: "2025-09-23",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-oct-1",  title: "Commissioners Court Meeting", date: "2025-10-14",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-oct-2",  title: "Commissioners Court Meeting", date: "2025-10-28",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-nov-1",  title: "Commissioners Court Meeting", date: "2025-11-18",  category: "Courts", description: "Harris County Commissioners Court regular meeting. (Moved from Nov 11: Veterans Day.)", importance: "normal" },
  { id: "cc-dec-1",  title: "Commissioners Court Meeting", date: "2025-12-09",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jan-1",  title: "Commissioners Court Meeting", date: "2026-01-13",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jan-2",  title: "Commissioners Court Meeting", date: "2026-01-27",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-feb-1",  title: "Commissioners Court Meeting", date: "2026-02-10",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-feb-2",  title: "Commissioners Court Meeting", date: "2026-02-24",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-mar-1",  title: "Commissioners Court Meeting", date: "2026-03-10",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-mar-2",  title: "Commissioners Court Meeting", date: "2026-03-24",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-apr-1",  title: "Commissioners Court Meeting", date: "2026-04-14",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-apr-2",  title: "Commissioners Court Meeting", date: "2026-04-28",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-may-1",  title: "Commissioners Court Meeting", date: "2026-05-12",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-may-2",  title: "Commissioners Court Meeting", date: "2026-05-26",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jun-1",  title: "Commissioners Court Meeting", date: "2026-06-09",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jun-2",  title: "Commissioners Court Meeting", date: "2026-06-23",  category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jul-1-26", title: "Commissioners Court Meeting", date: "2026-07-09", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-jul-2-26", title: "Commissioners Court Meeting", date: "2026-07-21", category: "Courts", description: "Harris County Commissioners Court meeting (Business Court session).", importance: "normal" },
  { id: "cc-jul-3-26", title: "Commissioners Court Meeting", date: "2026-07-30", category: "Courts", description: "Harris County Commissioners Court meeting (Business Court session).", importance: "normal" },
  { id: "cc-budget-hearings-2026", title: "Commissioners Court FY2026-2027 Budget Hearings", date: "2026-07-13", endDate: "2026-07-16", category: "Courts", description: "Harris County Commissioners Court holds FY2026-2027 budget hearings, Monday-Thursday at 10 AM, ahead of the Sep 29 budget adoption vote.", importance: "high" },
  { id: "cc-aug-1-26", title: "Commissioners Court Meeting", date: "2026-08-06", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-special-aug17-26", title: "Commissioners Court Special Meeting", date: "2026-08-17", category: "Courts", description: "Harris County Commissioners Court special meeting, 9 AM. Agenda not yet posted as of Jul 9 — check agenda.harriscountytx.gov closer to the date.", importance: "high" },
  { id: "cc-aug-2-26", title: "Commissioners Court Meeting", date: "2026-08-25", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-sep-1-26", title: "Commissioners Court Meeting", date: "2026-09-08", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-sep-2-26", title: "Commissioners Court Meeting", date: "2026-09-22", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-budget-2026-adopt", title: "Commissioners Court Budget Adoption", date: "2026-09-29", category: "Courts", description: "Commissioners Court adopts the FY2027 annual budget.", importance: "high" },
  { id: "cc-oct-1-26", title: "Commissioners Court Meeting", date: "2026-10-13", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-oct-2-26", title: "Commissioners Court Meeting", date: "2026-10-27", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-nov-1-26", title: "Commissioners Court Meeting", date: "2026-11-10", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-nov-2-26", title: "Commissioners Court Meeting", date: "2026-11-17", category: "Courts", description: "Harris County Commissioners Court regular meeting.", importance: "normal" },
  { id: "cc-budget-2026", title: "Commissioners Court Budget Adoption", date: "2025-09-30", category: "Courts", description: "Commissioners Court typically adopts the annual budget by September 30.", importance: "high" },
  // ── Houston City Council ─────────────────────────────────────────────────
  { id: "hcc-jul",    title: "Houston City Council Meeting", date: "2025-07-09", category: "City Council", description: "Houston City Council meets Wednesdays at 9 AM. Full agendas at houstontx.gov/citysec.", importance: "normal" },
  { id: "hcc-aug",    title: "Houston City Council Meeting", date: "2025-08-06", category: "City Council", description: "Houston City Council weekly session. Public comment accepted at the start.", importance: "normal" },
  { id: "hcc-sep",    title: "Houston City Council Meeting", date: "2025-09-10", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-oct",    title: "Houston City Council Meeting", date: "2025-10-08", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-nov",    title: "Houston City Council Meeting", date: "2025-11-12", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-dec",    title: "Houston City Council Meeting", date: "2025-12-10", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jan26",  title: "Houston City Council Meeting", date: "2026-01-14", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-feb26",  title: "Houston City Council Meeting", date: "2026-02-11", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-mar26",  title: "Houston City Council Meeting", date: "2026-03-11", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-apr26",  title: "Houston City Council Meeting", date: "2026-04-08", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-may26",  title: "Houston City Council Meeting", date: "2026-05-13", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jun26a", title: "Houston City Council Meeting", date: "2026-06-03", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jun26b", title: "Houston City Council Meeting", date: "2026-06-10", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jun26c", title: "Houston City Council Meeting", date: "2026-06-17", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jun26d", title: "Houston City Council Meeting", date: "2026-06-24", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jul26a", title: "Houston City Council Meeting", date: "2026-07-08", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-bfa-jul13-26", title: "Budget & Fiscal Affairs Committee Meeting", date: "2026-07-13", category: "City Council", description: "Houston City Council Budget & Fiscal Affairs Committee hears the Monthly Financial Report from City Controller Chris Hollins and Finance Director Melissa Dubowski.", importance: "normal" },
  { id: "hcc-jul26b", title: "Houston City Council Meeting", date: "2026-07-15", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-jul26c", title: "Houston City Council Meeting", date: "2026-07-22", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-propa-jul28-26", title: "Proposition A Committee Meeting", date: "2026-07-28", category: "City Council", description: "Houston City Council Proposition A Committee considers CM Willie Davis's ordinance creating a new Code of Ordinances \"Load Securement\" requirement, making it a criminal offense to transport unsecured cargo on Houston streets.", importance: "normal" },
  { id: "hcc-jul26d", title: "Houston City Council Meeting", date: "2026-07-29", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-aug26b", title: "Houston City Council Meeting", date: "2026-08-12", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-aug26c", title: "Houston City Council Meeting", date: "2026-08-19", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-aug26d", title: "Houston City Council Meeting", date: "2026-08-26", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-sep26a", title: "Houston City Council Meeting", date: "2026-09-09", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-sep26b", title: "Houston City Council Meeting", date: "2026-09-16", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-sep26c", title: "Houston City Council Meeting", date: "2026-09-23", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-sep26d", title: "Houston City Council Meeting", date: "2026-09-30", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-oct26a", title: "Houston City Council Meeting", date: "2026-10-07", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-oct26b", title: "Houston City Council Meeting", date: "2026-10-14", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-oct26c", title: "Houston City Council Meeting", date: "2026-10-21", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-oct26d", title: "Houston City Council Meeting", date: "2026-10-28", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-nov26a", title: "Houston City Council Meeting", date: "2026-11-04", category: "City Council", description: "Houston City Council weekly session.", importance: "normal" },
  { id: "hcc-budget", title: "Houston City Budget Adoption",  date: "2025-06-11", category: "City Council", description: "Houston City Council votes on the FY2026 budget. The city fiscal year begins July 1.", importance: "high" },
  // ── HISD Board ──────────────────────────────────────────────────────────
  { id: "hisd-jul",   title: "HISD Board of Managers Meeting", date: "2025-07-10", category: "HISD", description: "Houston ISD Board of Managers regular monthly meeting at Hattie Mae White Educational Support Center.", importance: "normal" },
  { id: "hisd-aug",   title: "HISD Board of Managers Meeting", date: "2025-08-14", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-sep",   title: "HISD Board of Managers Meeting", date: "2025-09-11", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-oct",   title: "HISD Board of Managers Meeting", date: "2025-10-09", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-nov",   title: "HISD Board of Managers Meeting", date: "2025-11-13", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-dec",   title: "HISD Board of Managers Meeting", date: "2025-12-11", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-jan26", title: "HISD Board of Managers Meeting", date: "2026-01-08", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-feb26", title: "HISD Board of Managers Meeting", date: "2026-02-12", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-mar26", title: "HISD Board of Managers Meeting", date: "2026-03-12", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-apr26", title: "HISD Board of Managers Meeting", date: "2026-04-09", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-may26", title: "HISD Board of Managers Meeting", date: "2026-05-14", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-jun26", title: "HISD Board of Managers Meeting", date: "2026-06-11", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-jul26", title: "HISD Board of Managers Meeting", date: "2026-07-09", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-aug26", title: "HISD Board of Managers Meeting", date: "2026-08-13", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-sep26", title: "HISD Board of Managers Meeting", date: "2026-09-10", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-oct26", title: "HISD Board of Managers Meeting", date: "2026-10-08", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-nov26", title: "HISD Board of Managers Meeting", date: "2026-11-12", category: "HISD", description: "HISD Board of Managers regular monthly meeting.", importance: "normal" },
  { id: "hisd-back-26", title: "HISD First Day of School", date: "2026-08-10", category: "HISD", description: "First day of the 2026-2027 Houston ISD school year.", importance: "normal" },
  { id: "hisd-budget",       title: "HISD Budget Adoption",     date: "2025-06-26", category: "HISD", description: "HISD Board of Managers adopts the annual district budget.", importance: "high" },
  { id: "hisd-back-to-school", title: "HISD First Day of School", date: "2025-08-11", category: "HISD", description: "First day of the 2025-2026 Houston ISD school year.", importance: "normal" },
  // ── Civic ────────────────────────────────────────────────────────────────
  { id: "lwv-jul-25",   title: "LWV Houston Monthly Meeting",     date: "2025-07-21", category: "Civic", description: "League of Women Voters of Houston monthly member meeting. Open to members and prospective members.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-aug-25",   title: "LWV Houston Monthly Meeting",     date: "2025-08-18", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-sep-25",   title: "LWV Houston Monthly Meeting",     date: "2025-09-15", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-oct-25",   title: "LWV Houston Monthly Meeting",     date: "2025-10-20", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-nov-25",   title: "LWV Houston Monthly Meeting",     date: "2025-11-17", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-jan-26",   title: "LWV Houston Monthly Meeting",     date: "2026-01-19", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-voter-reg-26", title: "LWV Voter Registration Drive", date: "2026-01-26", category: "Civic", description: "LWV Houston hosts a voter registration drive ahead of the March primary. Volunteers needed.", importance: "high", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-feb-26",   title: "LWV Houston Monthly Meeting",     date: "2026-02-16", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-mar-26",   title: "LWV Houston Monthly Meeting",     date: "2026-03-16", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-apr-26",   title: "LWV Houston Monthly Meeting",     date: "2026-04-20", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-may-26",   title: "LWV Houston Monthly Meeting",     date: "2026-05-18", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-jun-26",   title: "LWV Houston Monthly Meeting",     date: "2026-06-15", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-jul-26",   title: "LWV Houston Monthly Meeting",     date: "2026-07-20", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-aug-26",   title: "LWV Houston Monthly Meeting",     date: "2026-08-17", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-sep-26",   title: "LWV Houston Monthly Meeting",     date: "2026-09-21", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-vreg-sep-26", title: "LWV Voter Registration Drive", date: "2026-09-26", category: "Civic", description: "LWV Houston voter registration drive ahead of the Oct 5 deadline for the November General Election.", importance: "high", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "lwv-oct-26",   title: "LWV Houston Monthly Meeting",     date: "2026-10-19", category: "Civic", description: "League of Women Voters of Houston monthly member meeting.", importance: "normal", location: { lat: 29.7390, lng: -95.4200, address: "2615 Southwest Fwy, Houston, TX" } },
  { id: "sn-assembly-jul-26", title: "Super Neighborhood Assembly", date: "2026-07-23", category: "Civic", description: "Houston Super Neighborhood Assembly quarterly gathering.", importance: "high", location: { lat: 29.7569, lng: -95.3677, address: "Houston City Hall, 901 Bagby St" } },
  { id: "sn-assembly-oct-26", title: "Super Neighborhood Assembly", date: "2026-10-22", category: "Civic", description: "Houston Super Neighborhood Assembly quarterly gathering.", importance: "high", location: { lat: 29.7569, lng: -95.3677, address: "Houston City Hall, 901 Bagby St" } },
  { id: "candidate-filing-open",  title: "Candidate Filing Opens. Nov 2026 General",    date: "2026-07-18", category: "Elections", description: "Filing period opens for candidates seeking a place on the November 3, 2026 General Election ballot.", importance: "high" },
  { id: "candidate-filing-close", title: "Candidate Filing Deadline. Nov 2026 General",  date: "2026-08-17", category: "Elections", description: "Last day to file as a candidate for the November 3, 2026 General Election.", importance: "high" },

  // ── Campaign Finance Filing Deadlines ───────────────────────────────────────
  // TEC semi-annual reports due Jan 15 and Jul 15 each year (covers 6-month periods)
  { id: "tec-jan-2026",  title: "TEC Semi-Annual Report Due (Jan)",  date: "2026-01-15", category: "Elections", description: "Texas Ethics Commission semi-annual campaign finance reports due. Covers July–December 2025 period. State and county candidates who file with TEC must submit.", importance: "high" },
  { id: "tec-jul-2026",  title: "TEC Semi-Annual Report Due (Jul)",  date: "2026-07-15", category: "Elections", description: "Texas Ethics Commission semi-annual campaign finance reports due. Covers January–June 2026 period. Key pre-general filing showing funds raised through the primary and runoff cycles.", importance: "high" },
  { id: "tec-jan-2027",  title: "TEC Semi-Annual Report Due (Jan)",  date: "2027-01-15", category: "Elections", description: "TEC semi-annual report covering July–December 2026 (post-general). Final 2026 election cycle financial disclosure.", importance: "high" },
  // FEC quarterly reports (federal candidates: Congress, Senate)
  { id: "fec-q2-2026",   title: "FEC Q2 2026 Quarterly Report Due", date: "2026-07-15", category: "Elections", description: "Federal Election Commission Q2 2026 report due (covers April–June 2026). U.S. Senate and Congressional candidates must report. Key pre-general snapshot.", importance: "high" },
  { id: "fec-q3-2026",   title: "FEC Q3 2026 Quarterly Report Due", date: "2026-10-15", category: "Elections", description: "FEC Q3 2026 report due (covers July–September 2026). Final FEC quarterly before the November general election.", importance: "high" },
  { id: "fec-pre-general-2026", title: "FEC Pre-General Report Due", date: "2026-10-22", category: "Elections", description: "FEC Pre-General Election report due (12 days before election). Covers through Oct 14, filed by Oct 22. Most current money-in-politics snapshot before Election Day.", importance: "high" },
  // COH (Houston City) reports
  { id: "coh-semi-jan-2026", title: "Houston COH Semi-Annual Report (Jan)", date: "2026-01-15", category: "Elections", description: "Houston City campaign finance semi-annual reports due for city candidates. Covers July–December 2025.", importance: "normal" },
  { id: "coh-semi-jul-2026", title: "Houston COH Semi-Annual Report (Jul)", date: "2026-07-15", category: "Elections", description: "Houston City campaign finance semi-annual reports due. Covers January–June 2026.", importance: "normal" },

  // ── 2027 Houston City Council Elections (odd-year municipal cycle) ─────────
  { id: "hcc-filing-open-2027",   title: "City Council Filing Opens. 2027 Municipal",    date: "2027-07-17", category: "Elections", description: "Candidate filing opens for Houston City Council, Mayor, City Controller, and other municipal offices on the November 2027 ballot.", importance: "high" },
  { id: "hcc-filing-close-2027",  title: "City Council Filing Deadline. 2027 Municipal", date: "2027-08-16", category: "Elections", description: "Last day to file as a candidate for Houston City Council and other municipal offices.", importance: "high" },
  { id: "hcc-vreg-2027",          title: "Voter Registration Deadline. 2027 Municipal",  date: "2027-10-04", category: "Elections", description: "Last day to register to vote for the November 2, 2027 Houston Municipal Election.", importance: "high" },
  { id: "hcc-ev-2027",            title: "Early Voting. 2027 Houston Municipal Election", date: "2027-10-18", endDate: "2027-10-29", category: "Elections", description: "Early voting period for the November 2 Houston Municipal Election. Mayor, City Council, and City Controller races.", importance: "high" },
  { id: "hcc-election-2027",      title: "Houston Municipal Election Day",                 date: "2027-11-02", category: "Elections", description: "Houston City Election Day. Voters choose Mayor, all 16 City Council seats, City Controller, and Houston ISD trustees.", importance: "high" },
  { id: "tirz2-q1-26",  title: "TIRZ 2 (Midtown) Board Meeting",      date: "2026-01-21", category: "Civic", description: "TIRZ 2 Midtown Management District quarterly board meeting.", importance: "normal", location: { lat: 29.7440, lng: -95.3800, address: "Midtown Houston (3000 Main St area)" } },
  { id: "tirz2-q2-26",  title: "TIRZ 2 (Midtown) Board Meeting",      date: "2026-04-15", category: "Civic", description: "TIRZ 2 Midtown Management District quarterly board meeting.", importance: "normal", location: { lat: 29.7440, lng: -95.3800, address: "Midtown Houston (3000 Main St area)" } },
  { id: "tirz16-q1-26", title: "TIRZ 16 (Uptown/Galleria) Board",     date: "2026-03-18", category: "Civic", description: "Uptown Houston TIRZ 16 board meeting.", importance: "normal", location: { lat: 29.7460, lng: -95.4620, address: "Uptown Houston District (1800 Post Oak Blvd)" } },
  { id: "sn-assembly-jan-26",  title: "Super Neighborhood Assembly", date: "2026-01-22", category: "Civic", description: "Houston Super Neighborhood Assembly quarterly gathering.", importance: "high", location: { lat: 29.7569, lng: -95.3677, address: "Houston City Hall, 901 Bagby St" } },
  { id: "sn-assembly-apr-26",  title: "Super Neighborhood Assembly", date: "2026-04-23", category: "Civic", description: "Houston Super Neighborhood Assembly quarterly gathering.", importance: "high", location: { lat: 29.7569, lng: -95.3677, address: "Houston City Hall, 901 Bagby St" } },
  { id: "naacp-aug-25",        title: "Houston NAACP Branch Meeting", date: "2025-08-19", category: "Civic", description: "Houston Branch NAACP monthly membership meeting.", importance: "normal", location: { lat: 29.7560, lng: -95.3580, address: "NAACP Houston office (4805 Mt Vernon St)" } },
  { id: "lulac-aug-25",        title: "LULAC Council Houston Meeting", date: "2025-08-26", category: "Civic", description: "League of United Latin American Citizens (LULAC) Council Houston monthly meeting.", importance: "normal", location: { lat: 29.7425, lng: -95.3680, address: "East Houston (2100 Navigation Blvd area)" } },
];
