export type Politician = {
  slug: string;
  name: string;
  office: string;
  district: string;
  chamber: "Senate" | "House" | "County" | "City" | "HISD";
  party: "D" | "R" | "NP";
  photo?: string;
  salary?: number;
  website?: string;
  govUrl?: string;
  twitter?: string;
  instagram?: string;
  facebook?: string;
  email?: string;
  // Bill tracker search name (last name used for LegiScan)
  legiscanName?: string;
};

export const POLITICIANS: Politician[] = [
  // ── Texas Senate ─────────────────────────────────────────────────────
  {
    slug: "carol-alvarado",
    name: "Carol Alvarado",
    office: "Texas State Senator",
    district: "SD-6",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    website: "https://senate.texas.gov/member.php?d=6",
    twitter: "SenAlvarado",
    legiscanName: "Alvarado",
  },
  {
    slug: "borris-miles",
    name: "Borris Miles",
    office: "Texas State Senator",
    district: "SD-13",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    website: "https://senate.texas.gov/member.php?d=13",
    legiscanName: "Miles",
  },
  {
    slug: "molly-cook",
    name: "Molly Cook",
    office: "Texas State Senator",
    district: "SD-15",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    website: "https://senate.texas.gov/member.php?d=15",
    legiscanName: "Cook",
  },
  {
    slug: "paul-bettencourt",
    name: "Paul Bettencourt",
    office: "Texas State Senator",
    district: "SD-7",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    website: "https://senate.texas.gov/member.php?d=7",
    legiscanName: "Bettencourt",
  },
  // ── Texas House ──────────────────────────────────────────────────────
  {
    slug: "senfronia-thompson",
    name: "Senfronia Thompson",
    office: "Texas State Representative",
    district: "HD-141",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=141",
    legiscanName: "Thompson",
  },
  {
    slug: "ann-johnson",
    name: "Ann Johnson",
    office: "Texas State Representative",
    district: "HD-134",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=134",
    legiscanName: "Johnson",
  },
  {
    slug: "ana-hernandez",
    name: "Ana Hernandez",
    office: "Texas State Representative",
    district: "HD-143",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=143",
    legiscanName: "Hernandez",
  },
  {
    slug: "armando-walle",
    name: "Armando Walle",
    office: "Texas State Representative",
    district: "HD-140",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=140",
    legiscanName: "Walle",
  },
  {
    slug: "mary-ann-perez",
    name: "Mary Ann Perez",
    office: "Texas State Representative",
    district: "HD-144",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=144",
    legiscanName: "Perez",
  },
  {
    slug: "harold-dutton",
    name: "Harold Dutton",
    office: "Texas State Representative",
    district: "HD-142",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=142",
    legiscanName: "Dutton",
  },
  {
    slug: "gene-wu",
    name: "Gene Wu",
    office: "Texas State Representative",
    district: "HD-137",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=137",
    legiscanName: "Wu",
  },
  {
    slug: "jolanda-jones",
    name: "Jolanda Jones",
    office: "Texas State Representative",
    district: "HD-147",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=147",
    legiscanName: "Jones",
  },
  {
    slug: "hubert-vo",
    name: "Hubert Vo",
    office: "Texas State Representative",
    district: "HD-149",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=149",
    legiscanName: "Vo",
  },
  {
    slug: "lauren-ashley-simmons",
    name: "Lauren Ashley Simmons",
    office: "Texas State Representative",
    district: "HD-146",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=146",
    legiscanName: "Simmons",
  },
  {
    slug: "alma-allen",
    name: "Alma Allen",
    office: "Texas State Representative",
    district: "HD-131",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=131",
    legiscanName: "Allen",
  },
  {
    slug: "christina-morales",
    name: "Christina Morales",
    office: "Texas State Representative",
    district: "HD-145",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=145",
    legiscanName: "Morales",
  },
  {
    slug: "charlene-ward-johnson",
    name: "Charlene Ward Johnson",
    office: "Texas State Representative",
    district: "HD-139",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=139",
    legiscanName: "Johnson",
  },
  {
    slug: "jon-rosenthal",
    name: "Jon Rosenthal",
    office: "Texas State Representative",
    district: "HD-135",
    chamber: "House",
    party: "D",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=135",
    legiscanName: "Rosenthal",
  },
  {
    slug: "lacey-hull",
    name: "Lacey Hull",
    office: "Texas State Representative",
    district: "HD-138",
    chamber: "House",
    party: "R",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=138",
    legiscanName: "Hull",
  },
  {
    slug: "tom-oliverson",
    name: "Tom Oliverson",
    office: "Texas State Representative",
    district: "HD-130",
    chamber: "House",
    party: "R",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=130",
    legiscanName: "Oliverson",
  },
  {
    slug: "dennis-paul",
    name: "Dennis Paul",
    office: "Texas State Representative",
    district: "HD-129",
    chamber: "House",
    party: "R",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=129",
    legiscanName: "Paul",
  },
  {
    slug: "greg-bonnen",
    name: "Greg Bonnen",
    office: "Texas State Representative",
    district: "HD-24",
    chamber: "House",
    party: "R",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=24",
    legiscanName: "Bonnen",
  },
  {
    slug: "mike-schofield",
    name: "Mike Schofield",
    office: "Texas State Representative",
    district: "HD-132",
    chamber: "House",
    party: "R",
    salary: 7200,
    website: "https://house.texas.gov/members/member-page/?district=132",
    legiscanName: "Schofield",
  },
  // ── Harris County ─────────────────────────────────────────────────────
  {
    slug: "lina-hidalgo",
    name: "Lina Hidalgo",
    office: "Harris County Judge",
    district: "Countywide",
    chamber: "County",
    party: "D",
    salary: 201787,
    website: "https://harriscountytx.gov/county-judge",
    twitter: "LinaHidalgoTX",
  },
  {
    slug: "rodney-ellis",
    name: "Rodney Ellis",
    office: "Harris County Commissioner",
    district: "Precinct 1",
    chamber: "County",
    party: "D",
    salary: 182474,
    website: "https://pct1.harriscountytx.gov",
    twitter: "RodneyEllis",
  },
  {
    slug: "adrian-garcia",
    name: "Adrian Garcia",
    office: "Harris County Commissioner",
    district: "Precinct 2",
    chamber: "County",
    party: "D",
    salary: 182474,
    website: "https://www.pct2.com",
    twitter: "AdrianGarciaTX",
  },
  {
    slug: "tom-ramsey",
    name: "Tom Ramsey",
    office: "Harris County Commissioner",
    district: "Precinct 3",
    chamber: "County",
    party: "R",
    salary: 182474,
    website: "https://pct3.harriscountytx.gov",
  },
  {
    slug: "jack-cagle",
    name: "Jack Cagle",
    office: "Harris County Commissioner",
    district: "Precinct 4",
    chamber: "County",
    party: "R",
    salary: 182474,
    website: "https://pct4.harriscountytx.gov",
  },
];
