export type Politician = {
  slug: string;
  name: string;
  office: string;
  district: string;
  chamber: "Senate" | "House" | "County" | "City" | "HISD";
  party: "D" | "R" | "NP";
  photo?: string;
  salary?: number;
  website?: string;
  govUrl?: string;
  twitter?: string;
  instagram?: string;
  facebook?: string;
  bluesky?: string;
  tiktok?: string;
  email?: string;
  // Bill tracker search name (last name used for LegiScan)
  legiscanName?: string;
  // Year first elected/sworn into current or prior public office
  termStart?: number;
  // Legislative committees this person sits on
  committees?: string[];
  // If they chair or vice-chair a committee
  committeeRoles?: { committee: string; role: "Chair" | "Vice Chair" }[];
  // Leadership roles: caucus, party, honorary (dean, etc.)
  roles?: ("caucus-chair" | "caucus-vice-chair" | "party-leader" | "dean" | "mayor" | "county-judge")[];
  // District racial/ethnic demographics (%, from Census ACS; add to 100)
  demographics?: {
    hispanic: number;
    black: number;
    white: number;
    asian: number;
    other: number;
    source?: string;
  };
};

export const POLITICIANS: Politician[] = [
  // ── Texas Senate ─────────────────────────────────────────────────────
  {
    slug: "carol-alvarado",
    name: "Carol Alvarado",
    office: "Texas State Senator",
    district: "SD-6",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d06/img/CA-2018_web.jpg",
    website: "https://senate.texas.gov/member.php?d=6",
    twitter: "SenAlvarado",
    legiscanName: "Alvarado",
    committees: ["Health & Human Services", "Finance", "Nominations"],
    roles: ["caucus-chair"],
  },
  {
    slug: "borris-miles",
    name: "Borris Miles",
    office: "Texas State Senator",
    district: "SD-13",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d13/img/Sen-Miles-2025-Headshot-web.jpg",
    website: "https://senate.texas.gov/member.php?d=13",
    legiscanName: "Miles",
    committees: ["Natural Resources & Economic Development", "Transportation"],
  },
  {
    slug: "molly-cook",
    name: "Molly Cook",
    office: "Texas State Senator",
    district: "SD-15",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d15/img/Cook_88-0807D-014-2025.jpg",
    website: "https://senate.texas.gov/member.php?d=15",
    legiscanName: "Cook",
    committees: ["Environment & Land Use", "Business & Commerce", "Education"],
    termStart: 2024,
  },
  {
    slug: "paul-bettencourt",
    name: "Paul Bettencourt",
    office: "Texas State Senator",
    district: "SD-7",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d07/img/headshot.jpg",
    website: "https://senate.texas.gov/member.php?d=7",
    legiscanName: "Bettencourt",
    committees: ["Finance", "Local Government", "Property Tax"],
    committeeRoles: [{ committee: "Local Government", role: "Chair" }],
  },
  {
    slug: "brandon-creighton",
    name: "Brandon Creighton",
    office: "Texas State Senator",
    district: "SD-4",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d04/img/headshot.jpg",
    website: "https://senate.texas.gov/member.php?d=4",
    legiscanName: "Creighton",
    committees: ["Agriculture", "Business & Commerce", "Higher Education"],
    committeeRoles: [{ committee: "Higher Education", role: "Chair" }],
  },
  {
    slug: "joan-huffman",
    name: "Joan Huffman",
    office: "Texas State Senator",
    district: "SD-17",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d17/img/headshot.jpg",
    website: "https://senate.texas.gov/member.php?d=17",
    legiscanName: "Huffman",
    committees: ["Criminal Justice", "Finance", "Redistricting"],
    committeeRoles: [{ committee: "Redistricting", role: "Chair" }, { committee: "Criminal Justice", role: "Chair" }],
  },
  {
    slug: "lois-kolkhorst",
    name: "Lois Kolkhorst",
    office: "Texas State Senator",
    district: "SD-18",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d18/img/headshot.jpg",
    website: "https://senate.texas.gov/member.php?d=18",
    legiscanName: "Kolkhorst",
    committees: ["Health & Human Services", "Business & Commerce", "Agriculture"],
    committeeRoles: [{ committee: "Health & Human Services", role: "Chair" }],
  },
  // ── Texas House ──────────────────────────────────────────────────────
  {
    slug: "senfronia-thompson",
    name: "Senfronia Thompson",
    office: "Texas State Representative",
    district: "HD-141",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4630.jpg",
    website: "https://house.texas.gov/members/member-page/?district=141",
    legiscanName: "Thompson",
    termStart: 1973,
    committees: ["Calendars", "Rules & Resolutions"],
    roles: ["dean"],
  },
  {
    slug: "ann-johnson",
    name: "Ann Johnson",
    office: "Texas State Representative",
    district: "HD-134",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3985.jpg",
    website: "https://house.texas.gov/members/member-page/?district=134",
    legiscanName: "Johnson",
    committees: ["Criminal Jurisprudence", "Judiciary & Civil Jurisprudence"],
  },
  {
    slug: "ana-hernandez",
    name: "Ana Hernandez",
    office: "Texas State Representative",
    district: "HD-143",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3155.jpg",
    website: "https://house.texas.gov/members/member-page/?district=143",
    legiscanName: "Hernandez",
    termStart: 2007,
    committees: ["County Affairs", "Culture, Recreation & Tourism"],
  },
  {
    slug: "armando-walle",
    name: "Armando Walle",
    office: "Texas State Representative",
    district: "HD-140",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4930.jpg",
    website: "https://house.texas.gov/members/member-page/?district=140",
    legiscanName: "Walle",
    termStart: 2009,
    committees: ["Public Health", "Natural Resources"],
    committeeRoles: [{ committee: "Public Health", role: "Vice Chair" }],
  },
  {
    slug: "mary-ann-perez",
    name: "Mary Ann Perez",
    office: "Texas State Representative",
    district: "HD-144",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2535.jpg",
    website: "https://house.texas.gov/members/member-page/?district=144",
    legiscanName: "Perez",
    termStart: 2013,
    committees: ["Transportation", "State Affairs"],
  },
  {
    slug: "harold-dutton",
    name: "Harold Dutton",
    office: "Texas State Representative",
    district: "HD-142",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2650.jpg",
    website: "https://house.texas.gov/members/member-page/?district=142",
    legiscanName: "Dutton",
    termStart: 1985,
    committees: ["Juvenile Justice & Family Issues", "Redistricting"],
    committeeRoles: [{ committee: "Juvenile Justice & Family Issues", role: "Chair" }],
  },
  {
    slug: "gene-wu",
    name: "Gene Wu",
    office: "Texas State Representative",
    district: "HD-137",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2865.jpg",
    website: "https://house.texas.gov/members/member-page/?district=137",
    legiscanName: "Wu",
    termStart: 2013,
    committees: ["Judiciary & Civil Jurisprudence", "Technology"],
    roles: ["caucus-vice-chair"],
  },
  {
    slug: "jolanda-jones",
    name: "Jolanda Jones",
    office: "Texas State Representative",
    district: "HD-147",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4105.jpg",
    website: "https://house.texas.gov/members/member-page/?district=147",
    legiscanName: "Jones",
    committees: ["Criminal Jurisprudence", "Appropriations"],
  },
  {
    slug: "hubert-vo",
    name: "Hubert Vo",
    office: "Texas State Representative (term ends Jan 2027 — lost May 2026 D runoff to Darlene Breaux)",
    district: "HD-149",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4900.jpg",
    website: "https://house.texas.gov/members/member-page/?district=149",
    legiscanName: "Vo",
    termStart: 2004,
    committees: ["Appropriations", "Business & Industry"],
  },
  {
    slug: "lauren-ashley-simmons",
    name: "Lauren Ashley Simmons",
    office: "Texas State Representative",
    district: "HD-146",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4765.jpg",
    website: "https://house.texas.gov/members/member-page/?district=146",
    legiscanName: "Simmons",
  },
  {
    slug: "alma-allen",
    name: "Alma Allen",
    office: "Texas State Representative",
    district: "HD-131",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2100.jpg",
    website: "https://house.texas.gov/members/member-page/?district=131",
    legiscanName: "Allen",
    termStart: 2005,
    committees: ["Public Education", "Higher Education"],
    committeeRoles: [{ committee: "Public Education", role: "Vice Chair" }],
  },
  {
    slug: "christina-morales",
    name: "Christina Morales",
    office: "Texas State Representative",
    district: "HD-145",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3910.jpg",
    website: "https://house.texas.gov/members/member-page/?district=145",
    legiscanName: "Morales",
  },
  {
    slug: "charlene-ward-johnson",
    name: "Charlene Ward Johnson",
    office: "Texas State Representative",
    district: "HD-139",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4785.jpg",
    website: "https://house.texas.gov/members/member-page/?district=139",
    legiscanName: "Johnson",
  },
  {
    slug: "jon-rosenthal",
    name: "Jon Rosenthal",
    office: "Texas State Representative",
    district: "HD-135",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3635.jpg",
    website: "https://house.texas.gov/members/member-page/?district=135",
    legiscanName: "Rosenthal",
  },
  {
    slug: "lacey-hull",
    name: "Lacey Hull",
    office: "Texas State Representative",
    district: "HD-138",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3975.jpg",
    website: "https://house.texas.gov/members/member-page/?district=138",
    legiscanName: "Hull",
  },
  {
    slug: "josh-flynn",
    name: "Josh Flynn",
    office: "Texas State Representative",
    district: "HD-127",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4150.jpg",
    website: "https://house.texas.gov/members/member-page/?district=127",
    legiscanName: "Flynn",
  },
  {
    slug: "briscoe-cain",
    name: "Briscoe Cain",
    office: "Texas State Representative",
    district: "HD-128",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3475.jpg",
    website: "https://house.texas.gov/members/member-page/?district=128",
    legiscanName: "Cain",
    committees: ["Judiciary & Civil Jurisprudence"],
    committeeRoles: [{ committee: "Judiciary & Civil Jurisprudence", role: "Chair" }],
  },
  {
    slug: "tom-oliverson",
    name: "Tom Oliverson",
    office: "Texas State Representative",
    district: "HD-130",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3535.jpg",
    website: "https://house.texas.gov/members/member-page/?district=130",
    legiscanName: "Oliverson",
    committees: ["Insurance", "Public Health"],
    committeeRoles: [{ committee: "Insurance", role: "Chair" }],
  },
  {
    slug: "dennis-paul",
    name: "Dennis Paul",
    office: "Texas State Representative",
    district: "HD-129",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3090.jpg",
    website: "https://house.texas.gov/members/member-page/?district=129",
    legiscanName: "Paul",
  },
  {
    slug: "greg-bonnen",
    name: "Greg Bonnen",
    office: "Texas State Representative",
    district: "HD-24",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2875.jpg",
    website: "https://house.texas.gov/members/member-page/?district=24",
    legiscanName: "Bonnen",
    committees: ["Appropriations", "Higher Education"],
    committeeRoles: [{ committee: "Appropriations", role: "Chair" }],
  },
  {
    slug: "mike-schofield",
    name: "Mike Schofield",
    office: "Texas State Representative",
    district: "HD-132",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3095.jpg",
    website: "https://house.texas.gov/members/member-page/?district=132",
    legiscanName: "Schofield",
  },
  {
    slug: "valoree-swanson",
    name: "Valoree Swanson",
    office: "Texas State Representative",
    district: "HD-150",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3600.jpg",
    website: "https://house.texas.gov/members/member-page/?district=150",
    legiscanName: "Swanson",
  },
  {
    slug: "mano-deayala",
    name: "Mano DeAyala",
    office: "Texas State Representative",
    district: "HD-133",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4055.jpg",
    website: "https://house.texas.gov/members/member-page/?district=133",
    legiscanName: "DeAyala",
    committees: ["Business & Industry", "State Affairs"],
  },
  {
    slug: "penny-morales-shaw",
    name: "Penny Morales Shaw",
    office: "Texas State Representative",
    district: "HD-148",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4035.jpg",
    website: "https://house.texas.gov/members/member-page/?district=148",
    legiscanName: "Shaw",
    committees: ["Public Education", "Culture, Recreation & Tourism"],
  },
  // ── Harris County ─────────────────────────────────────────────────────
  {
    slug: "lina-hidalgo",
    name: "Lina Hidalgo",
    office: "Harris County Judge",
    district: "Countywide",
    chamber: "County",
    party: "D",
    salary: 201787,
    photo: "/politicians/lina-hidalgo.jpg",
    website: "https://harriscountytx.gov/county-judge",
    twitter: "LinaHidalgoTX",
    termStart: 2019,
    roles: ["county-judge"],
    demographics: { hispanic: 43, black: 19, white: 27, asian: 8, other: 3, source: "Census ACS 2022 Harris County" },
  },
  {
    slug: "rodney-ellis",
    name: "Rodney Ellis",
    office: "Harris County Commissioner",
    district: "Precinct 1",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/rodney-ellis.jpg",
    website: "https://pct1.harriscountytx.gov",
    twitter: "RodneyEllis",
    termStart: 1990,
    demographics: { hispanic: 48, black: 32, white: 11, asian: 5, other: 4, source: "Census ACS 2022 PCT 1" },
  },
  {
    slug: "adrian-garcia",
    name: "Adrian Garcia",
    office: "Harris County Commissioner",
    district: "Precinct 2",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/adrian-garcia.jpg",
    website: "https://www.pct2.com",
    twitter: "AdrianGarciaTX",
    termStart: 2009,
    demographics: { hispanic: 61, black: 20, white: 11, asian: 5, other: 3, source: "Census ACS 2022 PCT 2" },
  },
  {
    slug: "tom-ramsey",
    name: "Tom Ramsey",
    office: "Harris County Commissioner",
    district: "Precinct 3",
    chamber: "County",
    party: "R",
    salary: 182474,
    photo: "/politicians/tom-ramsey.jpg",
    website: "https://pct3.harriscountytx.gov",
  },
  {
    slug: "lesley-briones",
    name: "Lesley Briones",
    office: "Harris County Commissioner",
    district: "Precinct 4",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/lesley-briones.webp",
    website: "https://pct4.harriscountytx.gov",
    twitter: "LesleyBriones",
    termStart: 2023,
  },

  // ── City of Houston ───────────────────────────────────────────────────
  // Source: houstontx.gov/council — verified June 2026
  {
    slug: "john-whitmire",
    name: "John Whitmire",
    office: "Mayor of Houston",
    district: "Citywide",
    chamber: "City",
    party: "D",
    salary: 275000,
    photo: "https://www.houstontx.gov/mayor/images/whitmire250.jpg",
    website: "https://www.houstontx.gov/mayor",
    twitter: "JohnWhitmire",
    termStart: 2024,
    roles: ["mayor"],
  },
  {
    slug: "amy-peck",
    name: "Amy Peck",
    office: "Houston City Council Member",
    district: "District A",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/peck500.jpg",
    website: "https://www.houstontx.gov/council/a/",
  },
  {
    slug: "tarsha-jackson",
    name: "Tarsha Jackson",
    office: "Houston City Council Member",
    district: "District B",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/jackson500.jpg",
    website: "https://www.houstontx.gov/council/b/",
  },
  {
    slug: "joe-panzarella",
    name: "Joe Panzarella",
    office: "Houston City Council Member",
    district: "District C",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/panzarella500.jpg",
    website: "https://www.houstontx.gov/council/c/",
  },
  {
    slug: "carolyn-evans-shabazz",
    name: "Carolyn Evans-Shabazz",
    office: "Houston City Council Member",
    district: "District D",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/evansshabazz500.jpg",
    website: "https://www.houstontx.gov/council/d/",
  },
  {
    slug: "fred-flickinger",
    name: "Fred Flickinger",
    office: "Houston City Council Member",
    district: "District E",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/flickinger500.jpg",
    website: "https://www.houstontx.gov/council/e/",
  },
  {
    slug: "tiffany-thomas",
    name: "Tiffany Thomas",
    office: "Houston City Council Member",
    district: "District F",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/thomas500.jpg",
    website: "https://www.houstontx.gov/council/f/",
  },
  {
    slug: "mary-nan-huffman",
    name: "Mary Nan Huffman",
    office: "Houston City Council Member",
    district: "District G",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/huffman500.jpg",
    website: "https://www.houstontx.gov/council/g/",
  },
  {
    slug: "mario-castillo",
    name: "Mario Castillo",
    office: "Houston City Council Member",
    district: "District H",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/castillo500.jpg",
    website: "https://www.houstontx.gov/council/h/",
  },
  {
    slug: "joaquin-martinez",
    name: "Joaquin Martinez",
    office: "Houston City Council Member",
    district: "District I",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/martinez500.jpg",
    website: "https://www.houstontx.gov/council/i/",
  },
  {
    slug: "edward-pollard",
    name: "Edward Pollard",
    office: "Houston City Council Member",
    district: "District J",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/pollard500.jpg",
    website: "https://www.houstontx.gov/council/j/",
  },
  {
    slug: "martha-castex-tatum",
    name: "Martha Castex-Tatum",
    office: "Houston City Council Member",
    district: "District K",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/castextatum500.jpg",
    website: "https://www.houstontx.gov/council/k/",
  },
  {
    slug: "julian-ramirez",
    name: "Julian Ramirez",
    office: "Houston City Council Member",
    district: "At-Large 1",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/ramirez500.jpg",
    website: "https://www.houstontx.gov/council/1/",
  },
  {
    slug: "willie-davis",
    name: "Willie Davis",
    office: "Houston City Council Member",
    district: "At-Large 2",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/daviswillie500.jpg",
    website: "https://www.houstontx.gov/council/2/",
  },
  {
    slug: "twila-carter",
    name: "Twila Carter",
    office: "Houston City Council Member",
    district: "At-Large 3",
    chamber: "City",
    party: "R",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/carter500.jpg",
    website: "https://www.houstontx.gov/council/3/",
  },
  {
    slug: "alejandra-salinas",
    name: "Alejandra Salinas",
    office: "Houston City Council Member",
    district: "At-Large 4",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/salinas500.jpg",
    website: "https://www.houstontx.gov/council/4/",
  },
  {
    slug: "sallie-alcorn",
    name: "Sallie Alcorn",
    office: "Houston City Council Member",
    district: "At-Large 5",
    chamber: "City",
    party: "D",
    salary: 62915,
    photo: "https://www.houstontx.gov/council/cmgallery/alcorn500.jpg",
    website: "https://www.houstontx.gov/council/5/",
  },
  {
    slug: "chris-hollins",
    name: "Chris Hollins",
    office: "Houston City Controller",
    district: "Citywide",
    chamber: "City",
    party: "D",
    salary: 174000,
    photo: "https://www.houstontx.gov/controller/images/hollins.jpg",
    website: "https://www.houstontx.gov/controller",
    twitter: "ChrisHollins",
  },

  // ── HISD Board of Managers (TEA-appointed) ───────────────────────────
  {
    slug: "judith-cruz",
    name: "Judith Cruz",
    office: "HISD Board of Managers",
    district: "Board Chair",
    chamber: "HISD",
    party: "NP",
    photo: "https://www.houstonisd.org/cms/lib/TX02215309/Centricity/Domain/10559/Cruz-Judith.jpg",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "kenneth-huewitt",
    name: "Kenneth Huewitt",
    office: "HISD Superintendent",
    district: "Districtwide",
    chamber: "HISD",
    party: "NP",
    photo: "https://www.houstonisd.org/cms/lib/TX02215309/Centricity/Domain/10559/Huewitt-Kenneth.jpg",
    website: "https://www.houstonisd.org",
  },
  {
    slug: "patricia-allen-hisd",
    name: "Patricia Allen",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    photo: "https://www.houstonisd.org/cms/lib/TX02215309/Centricity/Domain/10559/Allen-Patricia.jpg",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "adriana-tamez",
    name: "Adriana Tamez",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    photo: "https://www.houstonisd.org/cms/lib/TX02215309/Centricity/Domain/10559/Tamez-Adriana.jpg",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "paula-harris-hisd",
    name: "Paula Harris",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    photo: "https://www.houstonisd.org/cms/lib/TX02215309/Centricity/Domain/10559/Harris-Paula.jpg",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  // ── 2026 General Election Nominees ───────────────────────────────────────
  {
    slug: "letitia-plummer",
    name: "Letitia Plummer",
    office: "Harris County Judge (D nominee 2026)",
    district: "Countywide",
    chamber: "County",
    party: "D",
    termStart: 2027,
  },
  {
    slug: "orlando-sanchez",
    name: "Orlando Sanchez",
    office: "Harris County Judge (R nominee 2026)",
    district: "Countywide",
    chamber: "County",
    party: "R",
  },
  {
    slug: "darlene-breaux",
    name: "Darlene Breaux",
    office: "Texas State Representative (D nominee HD-149 2026)",
    district: "HD-149",
    chamber: "House",
    party: "D",
    termStart: 2027,
  },
  {
    slug: "abbie-kamin",
    name: "Abbie Kamin",
    office: "Harris County Attorney (D nominee 2026)",
    district: "Countywide",
    chamber: "County",
    party: "D",
  },
  {
    slug: "mark-fury",
    name: "Mark Fury",
    office: "Justice of the Peace PCT 5 PL 2 (R nominee 2026)",
    district: "PCT 5 PL 2",
    chamber: "County",
    party: "R",
  },
  {
    slug: "lisa-jefferson",
    name: "Lisa Jefferson",
    office: "Justice of the Peace PCT 5 PL 2 (D nominee 2026)",
    district: "PCT 5 PL 2",
    chamber: "County",
    party: "D",
  },
  {
    slug: "melanie-miles",
    name: "Melanie Miles",
    office: "Justice of the Peace PCT 7 PL 2 (D nominee 2026)",
    district: "PCT 7 PL 2",
    chamber: "County",
    party: "D",
  },
  // 2026 State Legislature Nominees
  {
    slug: "shannon-dicely",
    name: "Shannon Dicely",
    office: "State Senator SD-11 (D nominee 2026)",
    district: "SD-11",
    chamber: "Senate",
    party: "D",
    termStart: 2027,
  },
  {
    slug: "stefanie-bord",
    name: "Stefanie Bord",
    office: "Texas State Representative (D nominee HD-126 2026)",
    district: "HD-126",
    chamber: "House",
    party: "D",
    termStart: 2027,
  },
  {
    slug: "stan-stanart",
    name: "Stan Stanart",
    office: "Texas State Representative (R nominee HD-126 2026)",
    district: "HD-126",
    chamber: "House",
    party: "R",
  },
  {
    slug: "staci-childs",
    name: "Staci Childs",
    office: "Texas State Representative (D nominee HD-131 2026)",
    district: "HD-131",
    chamber: "House",
    party: "D",
    termStart: 2027,
  },
];
