export type Politician = {
  slug: string;
  name: string;
  office: string;
  district: string;
  chamber: "Senate" | "House" | "County" | "City" | "HISD";
  party: "D" | "R" | "NP";
  photo?: string;
  salary?: number;
  website?: string;
  govUrl?: string;
  twitter?: string;
  instagram?: string;
  facebook?: string;
  email?: string;
  // Bill tracker search name (last name used for LegiScan)
  legiscanName?: string;
};

export const POLITICIANS: Politician[] = [
  // ── Texas Senate ─────────────────────────────────────────────────────
  {
    slug: "carol-alvarado",
    name: "Carol Alvarado",
    office: "Texas State Senator",
    district: "SD-6",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d06/img/CA-2018_web.jpg",
    website: "https://senate.texas.gov/member.php?d=6",
    twitter: "SenAlvarado",
    legiscanName: "Alvarado",
  },
  {
    slug: "borris-miles",
    name: "Borris Miles",
    office: "Texas State Senator",
    district: "SD-13",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d13/img/Sen-Miles-2025-Headshot-web.jpg",
    website: "https://senate.texas.gov/member.php?d=13",
    legiscanName: "Miles",
  },
  {
    slug: "molly-cook",
    name: "Molly Cook",
    office: "Texas State Senator",
    district: "SD-15",
    chamber: "Senate",
    party: "D",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d15/img/Cook_88-0807D-014-2025.jpg",
    website: "https://senate.texas.gov/member.php?d=15",
    legiscanName: "Cook",
  },
  {
    slug: "paul-bettencourt",
    name: "Paul Bettencourt",
    office: "Texas State Senator",
    district: "SD-7",
    chamber: "Senate",
    party: "R",
    salary: 7200,
    photo: "https://senate.texas.gov/members/d07/img/headshot.jpg",
    website: "https://senate.texas.gov/member.php?d=7",
    legiscanName: "Bettencourt",
  },
  // ── Texas House ──────────────────────────────────────────────────────
  {
    slug: "senfronia-thompson",
    name: "Senfronia Thompson",
    office: "Texas State Representative",
    district: "HD-141",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4630.jpg",
    website: "https://house.texas.gov/members/member-page/?district=141",
    legiscanName: "Thompson",
  },
  {
    slug: "ann-johnson",
    name: "Ann Johnson",
    office: "Texas State Representative",
    district: "HD-134",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3985.jpg",
    website: "https://house.texas.gov/members/member-page/?district=134",
    legiscanName: "Johnson",
  },
  {
    slug: "ana-hernandez",
    name: "Ana Hernandez",
    office: "Texas State Representative",
    district: "HD-143",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3155.jpg",
    website: "https://house.texas.gov/members/member-page/?district=143",
    legiscanName: "Hernandez",
  },
  {
    slug: "armando-walle",
    name: "Armando Walle",
    office: "Texas State Representative",
    district: "HD-140",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4930.jpg",
    website: "https://house.texas.gov/members/member-page/?district=140",
    legiscanName: "Walle",
  },
  {
    slug: "mary-ann-perez",
    name: "Mary Ann Perez",
    office: "Texas State Representative",
    district: "HD-144",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2535.jpg",
    website: "https://house.texas.gov/members/member-page/?district=144",
    legiscanName: "Perez",
  },
  {
    slug: "harold-dutton",
    name: "Harold Dutton",
    office: "Texas State Representative",
    district: "HD-142",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2650.jpg",
    website: "https://house.texas.gov/members/member-page/?district=142",
    legiscanName: "Dutton",
  },
  {
    slug: "gene-wu",
    name: "Gene Wu",
    office: "Texas State Representative",
    district: "HD-137",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2865.jpg",
    website: "https://house.texas.gov/members/member-page/?district=137",
    legiscanName: "Wu",
  },
  {
    slug: "jolanda-jones",
    name: "Jolanda Jones",
    office: "Texas State Representative",
    district: "HD-147",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4105.jpg",
    website: "https://house.texas.gov/members/member-page/?district=147",
    legiscanName: "Jones",
  },
  {
    slug: "hubert-vo",
    name: "Hubert Vo",
    office: "Texas State Representative",
    district: "HD-149",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4900.jpg",
    website: "https://house.texas.gov/members/member-page/?district=149",
    legiscanName: "Vo",
  },
  {
    slug: "lauren-ashley-simmons",
    name: "Lauren Ashley Simmons",
    office: "Texas State Representative",
    district: "HD-146",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4765.jpg",
    website: "https://house.texas.gov/members/member-page/?district=146",
    legiscanName: "Simmons",
  },
  {
    slug: "alma-allen",
    name: "Alma Allen",
    office: "Texas State Representative",
    district: "HD-131",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2100.jpg",
    website: "https://house.texas.gov/members/member-page/?district=131",
    legiscanName: "Allen",
  },
  {
    slug: "christina-morales",
    name: "Christina Morales",
    office: "Texas State Representative",
    district: "HD-145",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3910.jpg",
    website: "https://house.texas.gov/members/member-page/?district=145",
    legiscanName: "Morales",
  },
  {
    slug: "charlene-ward-johnson",
    name: "Charlene Ward Johnson",
    office: "Texas State Representative",
    district: "HD-139",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4785.jpg",
    website: "https://house.texas.gov/members/member-page/?district=139",
    legiscanName: "Johnson",
  },
  {
    slug: "jon-rosenthal",
    name: "Jon Rosenthal",
    office: "Texas State Representative",
    district: "HD-135",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3635.jpg",
    website: "https://house.texas.gov/members/member-page/?district=135",
    legiscanName: "Rosenthal",
  },
  {
    slug: "lacey-hull",
    name: "Lacey Hull",
    office: "Texas State Representative",
    district: "HD-138",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3975.jpg",
    website: "https://house.texas.gov/members/member-page/?district=138",
    legiscanName: "Hull",
  },
  {
    slug: "tom-oliverson",
    name: "Tom Oliverson",
    office: "Texas State Representative",
    district: "HD-130",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3535.jpg",
    website: "https://house.texas.gov/members/member-page/?district=130",
    legiscanName: "Oliverson",
  },
  {
    slug: "dennis-paul",
    name: "Dennis Paul",
    office: "Texas State Representative",
    district: "HD-129",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3090.jpg",
    website: "https://house.texas.gov/members/member-page/?district=129",
    legiscanName: "Paul",
  },
  {
    slug: "greg-bonnen",
    name: "Greg Bonnen",
    office: "Texas State Representative",
    district: "HD-24",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/2875.jpg",
    website: "https://house.texas.gov/members/member-page/?district=24",
    legiscanName: "Bonnen",
  },
  {
    slug: "mike-schofield",
    name: "Mike Schofield",
    office: "Texas State Representative",
    district: "HD-132",
    chamber: "House",
    party: "R",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/3095.jpg",
    website: "https://house.texas.gov/members/member-page/?district=132",
    legiscanName: "Schofield",
  },
  {
    slug: "penny-morales-shaw",
    name: "Penny Morales Shaw",
    office: "Texas State Representative",
    district: "HD-148",
    chamber: "House",
    party: "D",
    salary: 7200,
    photo: "https://house.texas.gov/images/members/4035.jpg",
    website: "https://house.texas.gov/members/member-page/?district=148",
    legiscanName: "Shaw",
  },
  // ── Harris County ─────────────────────────────────────────────────────
  {
    slug: "lina-hidalgo",
    name: "Lina Hidalgo",
    office: "Harris County Judge",
    district: "Countywide",
    chamber: "County",
    party: "D",
    salary: 201787,
    photo: "/politicians/lina-hidalgo.jpg",
    website: "https://harriscountytx.gov/county-judge",
    twitter: "LinaHidalgoTX",
  },
  {
    slug: "rodney-ellis",
    name: "Rodney Ellis",
    office: "Harris County Commissioner",
    district: "Precinct 1",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/rodney-ellis.jpg",
    website: "https://pct1.harriscountytx.gov",
    twitter: "RodneyEllis",
  },
  {
    slug: "adrian-garcia",
    name: "Adrian Garcia",
    office: "Harris County Commissioner",
    district: "Precinct 2",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/adrian-garcia.jpg",
    website: "https://www.pct2.com",
    twitter: "AdrianGarciaTX",
  },
  {
    slug: "tom-ramsey",
    name: "Tom Ramsey",
    office: "Harris County Commissioner",
    district: "Precinct 3",
    chamber: "County",
    party: "R",
    salary: 182474,
    photo: "/politicians/tom-ramsey.jpg",
    website: "https://pct3.harriscountytx.gov",
  },
  {
    slug: "lesley-briones",
    name: "Lesley Briones",
    office: "Harris County Commissioner",
    district: "Precinct 4",
    chamber: "County",
    party: "D",
    salary: 182474,
    photo: "/politicians/lesley-briones.webp",
    website: "https://pct4.harriscountytx.gov",
    twitter: "LesleyBriones",
  },

  // ── City of Houston ───────────────────────────────────────────────────
  {
    slug: "john-whitmire",
    name: "John Whitmire",
    office: "Mayor of Houston",
    district: "Citywide",
    chamber: "City",
    party: "D",
    salary: 275000,
    website: "https://www.houstontx.gov/mayor",
    twitter: "JohnWhitmire",
  },
  {
    slug: "amy-peck",
    name: "Amy Peck",
    office: "Houston City Council Member",
    district: "District A",
    chamber: "City",
    party: "R",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districta/",
  },
  {
    slug: "tarsha-jackson",
    name: "Tarsha Jackson",
    office: "Houston City Council Member",
    district: "District B",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districtb/",
  },
  {
    slug: "alejandra-salinas",
    name: "Alejandra Salinas",
    office: "Houston City Council Member",
    district: "District C",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districtc/",
  },
  {
    slug: "carolyn-evans-shabazz",
    name: "Carolyn Evans-Shabazz",
    office: "Houston City Council Member",
    district: "District D",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districtd/",
  },
  {
    slug: "willie-davis",
    name: "Willie Davis",
    office: "Houston City Council Member",
    district: "District E",
    chamber: "City",
    party: "R",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districte/",
  },
  {
    slug: "martha-castex-tatum",
    name: "Martha Castex-Tatum",
    office: "Houston City Council Member",
    district: "District F",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districtf/",
  },
  {
    slug: "twila-carter",
    name: "Twila Carter",
    office: "Houston City Council Member",
    district: "District G",
    chamber: "City",
    party: "R",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districtg/",
  },
  {
    slug: "joaquin-martinez",
    name: "Joaquin Martinez",
    office: "Houston City Council Member",
    district: "District H",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districth/",
  },
  {
    slug: "julian-ramirez",
    name: "Julian Ramirez",
    office: "Houston City Council Member",
    district: "District I",
    chamber: "City",
    party: "R",
    salary: 62915,
    website: "https://www.houstontx.gov/council/districti/",
  },
  {
    slug: "sallie-alcorn",
    name: "Sallie Alcorn",
    office: "Houston City Council Member",
    district: "At-Large 1",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/atlarge1/",
  },
  {
    slug: "ed-pollard",
    name: "Ed Pollard",
    office: "Houston City Council Member",
    district: "At-Large 2",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/atlarge2/",
  },
  {
    slug: "fred-flickinger",
    name: "Fred Flickinger",
    office: "Houston City Council Member",
    district: "At-Large 3",
    chamber: "City",
    party: "R",
    salary: 62915,
    website: "https://www.houstontx.gov/council/atlarge3/",
  },
  {
    slug: "tiffany-thomas",
    name: "Tiffany Thomas",
    office: "Houston City Council Member",
    district: "At-Large 4",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/atlarge4/",
  },
  {
    slug: "mario-castillo",
    name: "Mario Castillo",
    office: "Houston City Council Member",
    district: "At-Large 5",
    chamber: "City",
    party: "D",
    salary: 62915,
    website: "https://www.houstontx.gov/council/atlarge5/",
  },
  {
    slug: "chris-hollins",
    name: "Chris Hollins",
    office: "Houston City Controller",
    district: "Citywide",
    chamber: "City",
    party: "D",
    salary: 174000,
    website: "https://www.houstontx.gov/controller",
    twitter: "ChrisHollins",
  },

  // ── HISD Board of Managers (TEA-appointed) ───────────────────────────
  {
    slug: "judith-cruz",
    name: "Judith Cruz",
    office: "HISD Board of Managers",
    district: "Board Chair",
    chamber: "HISD",
    party: "NP",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "kenneth-huewitt",
    name: "Kenneth Huewitt",
    office: "HISD Superintendent",
    district: "Districtwide",
    chamber: "HISD",
    party: "NP",
    website: "https://www.houstonisd.org",
  },
  {
    slug: "patricia-allen-hisd",
    name: "Patricia Allen",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "adriana-tamez",
    name: "Adriana Tamez",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
  {
    slug: "paula-harris-hisd",
    name: "Paula Harris",
    office: "HISD Board of Managers",
    district: "Board Member",
    chamber: "HISD",
    party: "NP",
    website: "https://www.houstonisd.org/boardofmanagers",
  },
];
