/**
 * Known women in Harris County politics — covers current officeholders,
 * 2026 ballot candidates, and tracked campaign finance filers.
 * Used for the "W" badge across ballot, officials, and finance tools.
 */
export const WOMEN_IN_POLITICS = new Set([
  // U.S. Congress
  "Lizzie Fletcher",
  "Sylvia Garcia",
  // Texas Senate
  "Carol Alvarado",
  "Joan Huffman",
  "Lois Kolkhorst",
  // Texas House
  "Senfronia Thompson",
  "Ann Johnson",
  "Ana Hernandez",
  "Mary Ann Perez",
  "Jolanda Jones",
  "Lauren Ashley Simmons",
  "Alma Allen",
  "Christina Morales",
  "Charlene Ward Johnson",
  "Lacey Hull",
  "Penny Morales Shaw",
  // 2026 candidates (HD/SD)
  "Gina Hinojosa",
  "Letitia Plummer",
  "Laura Jones",
  "Leticia Gutierrez",
  "Marquette Greene-Scott",
  "Rhonda Hart",
  "Melissa McDonough",
  "Shannon Dicely",
  "Molly Cook",
  "Stefanie Bord",
  "Staci Childs",
  "Lacey Hull",
  "Charlene Ward Johnson",
  "Darlene Breaux",
  "A'Yonna Kellum",
  "Dolores Lozano",
  "Abbie Kamin",
  // Harris County
  "Lina Hidalgo",
  "Lesley Briones",
  "Annette Ramirez",
  "Marilyn Burgess",
  "Teneshia Hudspeth",
  "Carla Wyatt",
  "Lisa Jefferson",
  "Melanie Miles",
  "Silvia Trevino",
  // City of Houston
  "Amy Peck",
  "Tarsha Jackson",
  "Carolyn Evans-Shabazz",
  "Tiffany Thomas",
  "Mary Nan Huffman",
  "Martha Castex-Tatum",
  "Twila Carter",
  "Alejandra Salinas",
  "Sallie Alcorn",
  "Judith Cruz",
  "Patricia Allen",
  "Adriana Tamez",
  "Paula Harris",
  // Justice Courts
  "Jo Ann Delgado",
  "Lucia Bates",
  "Laryssa Korduba",
  "Angela D. Rodriguez",
  "Wanda E. Adams",
  "Sharon M. Burney",
  "Holly Williamson",
  // Criminal Courts at Law judges
  "Shannon Baldwin",
  "Kelley Andrews",
  "Erika Ramirez",
  "Toria J. Finch",
  "Juanita Jackson",
  "Ashley Mayes Guice",
  "Tonya Jones",
  "Leslie R. Johnson",
  "Linda Garcia",
  // CCL 2026 R nominees (women)
  "Erin Swanson",
  "Rebecca Phillips Aceto",
  "Stella Stevens",
  "Liz Buss",
  "Anna Emmons",
  "Amber Cox",
  "Yahaira Quezada",
  "Jessica N. Padilla",
  // Criminal District Court candidates (felony courts)
  "Stephanie Morales",
  "Tami Pierce",
  "Julia Maldonado",
  "Katherine Thomas",
  "Heather Hudson",
  "Andrea Beall",
  "Beverly Armstrong",
  "Alyson Almaguer",
  "Caroline Dozier",
  "Megan Long",
  "Hilary Unger",
  "Lori Chambers Gray",
  "Melissa Morris",
  "Veronica Nelson",
  "Tiffany Hill",
  "Lori DeAngelo",
  "Breanna Schwartz",
]);
