"use client";
import { useState, useEffect } from "react";

/* Admin-only data-freshness dashboard. Not linked from any nav — reachable only
   by URL (/admin/freshness) and noindexed via robots metadata in layout.tsx.
   Data comes from public/data/freshness.json, regenerated by `npm run check-freshness`. */

interface Row {
  name: string; path: string; frequency: string; maxAgeDays: number;
  mtime: string | null; ageDays: number | null; status: "current" | "stale" | "overdue" | "missing";
}

const COLORS: Record<Row["status"], { bg: string; fg: string }> = {
  current: { bg: "#dcfce7", fg: "#166534" },
  stale:   { bg: "#fef9c3", fg: "#854d0e" },
  overdue: { bg: "#fee2e2", fg: "#991b1b" },
  missing: { bg: "#f3f4f6", fg: "#6b7280" },
};

export default function FreshnessAdmin() {
  const [data, setData] = useState<{ generated: string; rows: Row[] } | null>(null);
  const [err, setErr] = useState(false);

  useEffect(() => {
    fetch("/data/freshness.json").then(r => r.json()).then(setData).catch(() => setErr(true));
  }, []);

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[var(--muted)] mb-2">Admin · Internal</p>
      <h1 className="text-2xl font-bold mb-1" style={{ fontFamily: "var(--font-playfair), serif", color: "#1a3a5c" }}>
        Data Freshness
      </h1>
      <p className="text-sm text-[var(--muted)] mb-8">
        Snapshot from <code>npm run check-freshness</code>
        {data && <> — generated {new Date(data.generated).toLocaleString("en-US")}</>}.
        Re-run the script and redeploy to refresh.
      </p>

      {err && (
        <div className="empty-state">
          <p className="font-semibold text-sm">No freshness snapshot found.</p>
          <p className="text-xs">Run <code>npm run check-freshness</code> locally and deploy — it writes public/data/freshness.json.</p>
        </div>
      )}
      {!data && !err && <div className="skeleton" style={{ height: 320 }} />}

      {data && (
        <div className="hcp-card overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-[10px] uppercase tracking-wider text-[var(--muted)]" style={{ borderBottom: "1px solid var(--border)" }}>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Source</th>
                <th className="px-4 py-3 hidden md:table-cell">File</th>
                <th className="px-4 py-3 text-right">Updated</th>
                <th className="px-4 py-3 text-right">Age</th>
                <th className="px-4 py-3 text-right hidden sm:table-cell">Window</th>
              </tr>
            </thead>
            <tbody>
              {data.rows.map(r => (
                <tr key={r.path} style={{ borderBottom: "1px solid #f3f4f6" }}>
                  <td className="px-4 py-2.5">
                    <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-full"
                      style={{ background: COLORS[r.status].bg, color: COLORS[r.status].fg }}>
                      {r.status}
                    </span>
                  </td>
                  <td className="px-4 py-2.5 font-medium" style={{ color: "#1a3a5c" }}>{r.name}</td>
                  <td className="px-4 py-2.5 hidden md:table-cell"><code className="text-[11px] text-[var(--muted)]">{r.path}</code></td>
                  <td className="px-4 py-2.5 text-right tnum text-xs">{r.mtime ?? "—"}</td>
                  <td className="px-4 py-2.5 text-right tnum text-xs">{r.ageDays ?? "—"}d</td>
                  <td className="px-4 py-2.5 text-right tnum text-xs hidden sm:table-cell">{r.maxAgeDays}d</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <p className="text-[11px] text-[var(--muted)] mt-4">
        File mtimes are a proxy — a fresh git clone resets them. Treat yellow/red as a prompt to verify the source, not proof it&rsquo;s wrong.
      </p>
    </div>
  );
}
